### ISSUE TITLE
[Recipe Conflict] XL Foods Ground Beef <-> Bird's Food Sliced Steak

### ISSUE THREAD

**Issue by ShaneCourtrille** [AllTheMods/ATM3-Remix#102]
The Ground Beef recipe from XL Foods has a conflict with Sliced Steak from Bird's Food which wouldn't be as big a problem except ground beef isn't cross mod compatible so puts a few good recipes out of reach.

**Comment by FallenEagle1** [comment]
Update is live with the fix.
