### ISSUE TITLE
Extreme Reactors Loop

### ISSUE THREAD

**Issue by FallenEagle1** [AllTheMods/ATM3-Remix#103]
Check into blutonium->cyanite->blutonium->etc loop.

**Comment by Yoosk** [comment]
I cant find the way to make blutionium from cyanite, maybe it changed with latest updates of mods?

**Comment by ReiDaTecnologia** [comment]
iirc you use cyanite liquid form in the Fractionating Still and it give blutonium (Together with a little of menril as output liquid) and you also can get it as bonus output from processing uranium.

**Comment by Yoosk** [comment]
Bonus output from uranium seems fine for me. However i will remove it from fractionating still, that will serve only to make menril from cyanite.

**Comment by ReiDaTecnologia** [comment]
tbh imo get little of menril as output is not a really big issue... it's not like it is outputting liquid draconium... after all menril is only used by integrated dynamics to do the items and blocks from the mod.

**Comment by Yoosk** [comment]
That recipe was made on purpose and will stay as such.

**Comment by Sleeeper** [comment]
if you remove recipe using fractionating still, how else to make blutonium then, there is no other way.
