### ISSUE TITLE
Gendustry Resource Listener Crash

### ISSUE THREAD

**Issue by Yamza** [AllTheMods/ATM3-Remix#104]
Client crashes on loading, seems to effect a small number of people.
gendustry-1.6.5.8-mc1.12.2.jar  

User: broider 11/21/2018
https://pastebin.com/LmR9Seqx

User: JaniB 12/9/2018
https://pastebin.com/60w4cTMi

Related issue reports:
https://github.com/bdew/gendustry/issues/286
https://github.com/bdew/gendustry/issues/271

Potential solution: Disable foamfix coremod functionality.

**Comment by Yoosk** [comment]
I won't disable coremod functionality overall for whole modpack as it helps with with already big RAM allocation. I'f someone has issue as above, he should disable it alone for now.

**Comment by Yamza** [comment]
Just want to update that the recommended solution did not work.
