### ISSUE TITLE
[Suggestion] Remove the Quark TrashCan

### ISSUE THREAD

**Issue by ReiDaTecnologia** [AllTheMods/ATM3-Remix#107]
## Expected Behavior

Exist only one trashcan, in this case, the ftbu one.

## Current Behavior

The Quark trashcan keep in the inventory gui even when you open others gui. This can be very dangerous because you can accidentally delete a item and also it sometimes bug in some blocks/machines gui and keep in the way of something like a important text or option. Like the Auto Anvil from the OpenBlocks. 

## Possible Solution

Config: quark.cfg
Line 793:
B:"Enable Trash Button"=true
to
B:"Enable Trash Button"=false

## Steps to Reproduce

1. Press E to open you inventory
2. You can see it in the bottom right.

## Log

N/A

## Detailed Description

I lost two items because of this trashcan ;-;

**Comment by Leucetius** [comment]
For the accidentally deleting items: the dev stated that in an upcoming Update you have to shift-click an item onto the trashcan to trash it.

**Comment by Yoosk** [comment]
I can take that as resolved with upcoming update.
