### ISSUE TITLE
Is vanilla Interconnect recipe supposed to be disabled?

### ISSUE THREAD

**Issue by Damien-Reave** [AllTheMods/ATM3-Remix#110]
The modded recipe is so much tougher I suspect it was intended that the vanilla recipe be disabled.

**Comment by FallenEagle1** [comment]
Both of the interconnect recipes are from env tech. I didnt even know a second was added. Will look into it closer though

**Comment by Sleeeper** [comment]
Harder recipe is useful for faster autocrafting (no fluid transposer involved) when you have spare resources

**Comment by FallenEagle1** [comment]
I'll leave it as is for now, will see what changes the dev makes along the way.
