### ISSUE TITLE
NuclearCraft RadAway item recipe is missing

### ISSUE THREAD

**Issue by MelficeSilesius** [AllTheMods/ATM3-Remix#120]
## Expected Behavior
The RadAway ITEM (!!!not the fluid!!!) should be able to be created in one of the machines.

## Current Behavior
There is no recipe associated with the item's creation. This is an issue in NuclearCraft itself, not with the configs!

## Possible Solution
This issue is fixed in the latest (2.13) version of NuclearCraft, meaning the mod needs to be updated in the pack.

## Steps to Reproduce

1. Is this really necessary? I mean... fine, I guess?
2. Search for RadAway in JEI.
3. Click on, or press "R" when hovered over the ITEM FORM of RadAway. NOT the RadAway Fluid.
4. See that there is no recipe to create the item.

**Comment by Yoosk** [comment]
![obraz](https://user-images.githubusercontent.com/4502802/51074827-af56ca80-167b-11e9-9d5c-849921f4e039.png)

**Comment by MelficeSilesius** [comment]
I obviously missed some place to look then. I checked everywhere to see if this was reported already.

My bad! Good job, y'all, and carry on as you were!
