### ISSUE TITLE
Quark Quick Chest Deposit / Chest Buttons

### ISSUE THREAD

**Issue by Spyboticsguy** [AllTheMods/ATM3-Remix#122]
Currently, the Quark feature to quickly deposit items to nearby chests (as well as merge to nearby chests) is disabled. Currently, you can deposit and merge to a chest or other supported container if you have that container's GUI open, but the buttons to simply store or merge to all nearby chests from the player inventory GUI is disabled.

My suggestion would be to enable this feature. Having tested locally, I have identified a number of issues with enabling the feature, as well as some of the other existing issues surrounding Quark's inventory management.

Will add screenshots for the relevant sections as soon as I am able.

## Known Issues 
- [ ] Two of the Quark chest interaction buttons slightly overlap when opening a chest or container (extract and restock).
- [ ] Some container GUIs do not have Quark chest management support.
  - Immersive Engineering crates
  - Actually Additions crates
  - Several other storage containers that use a generic GUI class and thus cannot have Quark support added (e.g. TechReborn)
  - Still identifying containers that don't have support. More to be added.

## Issues Introduced by Enhancement
- [ ] Adding support for the other containers can cause Quark chest buttons to overlap other GUI elements (no examples currently, but I am getting screenshots).
- [ ] Quark button for chest deposit in player inventory overlaps with Nutrition button.
  - Fairly simple fix is to move the position of the Quark button or the Nutrition button.

## Other Information
Many mods use a single GUI class for their machines and blocks. As an example, TechReborn uses AdvancedGUI.class for most of its machinery, making it impractical to enable Quark chest buttons on its storage containers, as the buttons would then begin appearing on non-storage blocks from that mod.

### Finding container GUI names
To identify the GUI classes of containers, Quark offers a debug configuration option that will print container GUI classnames to the log. This can be enabled in `quark.cfg` by setting the `"Debug Classnames"` option to `true`:
```
...
management {
    ...
    "chest buttons" {
        # Set this to true to print out the names of all GUIs you open to the log. This is used to fill in the "Forced GUIs" list.
        B:"Debug Classnames"=true
        ...
    }
    ...
}
```
To force the chest buttons to show up, you then add the discovered classnames to the `"Forced GUIs"` option immediately below.
```
...
management {
    ...
    "chest buttons" {
        # Set this to true to print out the names of all GUIs you open to the log. This is used to fill in the "Forced GUIs" list.
        B:"Debug Classnames"=true

        # GUIs in which the chest buttons should be forced to show up. Use the "Debug Classnames" option to find the names.
        S:"Forced GUIs" <
            this.is.an.example.ContainerGUI
            another.class.here.BigChest
         >
    }
    ...
}
```

### Enabling Store to Chest
The configuration options for storing to nearby chests are contained in the same section as the container GUI overrides. To enable the feature, simply change the configuration value `"Store to chests"` to `true`. The position of the GUI element can be adjusted using the configuration values immediately following.

Toggling the `"Invert button"` option to `true` will cause the store button to default to merging to nearby chests (i.e. only depositing items which are already in those containers).
```
management {
    ...
    B:"Store to chests"=true

    "store to chests" {
        ...
        # If true the default will be to merge your items into nearby chests, otherwise hold shift for this functionality.
        B:"Invert button"=false
        I:"Position X"=0
        I:"Position X (Creative)"=28
        I:"Position Y "=30
        I:"Position Y (Creative)"=-20
    }
    ...
}
```

### Adjusting Chest Button Position
As mentioned, there are already some overlaps with Quark chest buttons without enabling the feature, and enabling the feature for other containers may cause the elements to overlap with other important GUI elements.

The position of each button can be adjusted in `quark.cfg` in the `"chest buttons"` section of the `management` module. This configuration section also allows for the individual buttons to be toggled on and off as desired.
```
management {
    ...
    "chest buttons" {
        ...
        deposit {
            #  [default: true]
            B:Enabled=true

            #  [range: -2147483648 ~ 2147483647, default: -18]
            I:"X Position"=-18

            #  [range: -2147483648 ~ 2147483647, default: -50]
            I:"Y Position"=-50
        }

        smart_deposit {
            #  [default: true]
            B:Enabled=true

            #  [range: -2147483648 ~ 2147483647, default: -18]
            I:"X Position"=-18

            #  [range: -2147483648 ~ 2147483647, default: -30]
            I:"Y Position"=-30
        }

        restock {
            #  [default: true]
            B:Enabled=true

            #  [range: -2147483648 ~ 2147483647, default: -18]
            I:"X Position"=-18

            #  [range: -2147483648 ~ 2147483647, default: 45]
            I:"Y Position"=35
        }

        extract {
            #  [default: true]
            B:Enabled=true

            #  [range: -2147483648 ~ 2147483647, default: -18]
            I:"X Position"=-18

            #  [range: -2147483648 ~ 2147483647, default: 25]
            I:"Y Position"=25
        }
        ...
    }
    ...
}
```

**Comment by Spyboticsguy** [comment]
I would suggest the enhancement label for this issue, as it is a request more than a bug report.

**Comment by Asheneyes** [comment]
"To identify the GUI classes of containers, Quark offers a debug configuration option that will print container GUI classnames to the log. This can be enabled in quark.cfg by setting the "Debug Classnames" option to true:"

What log... where? I am setting this value to true but it is definitely not posting the Classname into the chat log.
