### ISSUE TITLE
Primitive Mobs configs

### ISSUE THREAD

**Issue by Darkere** [AllTheMods/ATM3-Remix#124]
- Grove Sprites are currently conflicting with nuclear craft Radiation. 
![image](https://user-images.githubusercontent.com/4283717/51275484-6764da00-19d2-11e9-8050-6eef0265ccff.png)

- Voideyes are not fun. An enemy that blinds and poisons you only to teleport away to an unexplored part of the cave system once attacked is more obnoxious than fun.

**Comment by Yamza** [comment]
Please disable, senpai!
