### ISSUE TITLE
OreDict conflicts | Ingot conversion

### ISSUE THREAD

**Issue by Schildos** [AllTheMods/ATM3-Remix#127]
## Expected Behavior
- Output from myst. agriculture essence should be thermal ingots, but isn't for any of the ingots that ic2 registers as well
- Ingot conversion recipe does not seem to work
- Gear recipes do not recognize universal ingots (which'd have made above parts less annoying)

## Current Behavior
Output for the essences are IC2 ingots,
The Conversion recipe does nothing
The Gears are only craftable using Thermal ingots

## Possible Solution
overwrite the gear recipes to use <ore:{ingotType}>
overwrite the essence recipes to output thermal ingots instead of ic2 ingots
Verify the code for the conversion recipes? (not sure about that one kinda)

## Steps to Reproduce
1. Go ingame, check the recipes and their outputs

#Requested by FallenAngel16.

**Comment by FallenEagle1** [comment]
Looked into the problem some, this issue actually comes from some bugs in the mod Unidict. Can't easily change anything with this until the mod updates and fixes the issue.
