### ISSUE TITLE
KB: Known Issues with Spongeforge

### ISSUE THREAD

**Issue by derrickmehaffy** [AllTheMods/ATM3-Remix#13]
During the previous testing and bug threads before ATM3R was created I noticed a few people testing with Spongeforge. Is this type of testing still going on or is the standard "Don't use spongeforge" answer still the default?

I plan on doing some testing myself but wanted to see if anyone else had some information to share on this.

(PS don't shoot me, just wanted to get some info before I do my own testing)

**Comment by FallenEagle1** [comment]
Sponge tends to add bugs, so if you have specific plugins in mind that have functionality that isn;t already in the game it can be used. I find it tends to be more of a hassle than not, but it seems to be usable. What plugins where you hoping to use? It seems like the common one's most people think of, there are sometimes that functionality in the game already.

**Comment by KaneHart** [comment]
It will work. Is it worth it? Depends on your needs but honestly Sponge Forge is buggy like Fallen said and will give you none stop issues and troubles. We also recommend testing all bugs that you had with Sponge Forge in Normal Forge before reporting them as it's very annoying in the end when it's a Sponge bug lol.

**Comment by derrickmehaffy** [comment]
@KaneHart yeah of course, not new to reporting bugs. I just wondering if anyone had come across any to mention.

@FallenEagle1 I didn't have anything specific in mind for the moment, more so the thought of being able to load in additional "options" that won't require my users to modify their clients beyond the normal ATM3R (as we know, users can be quite.... slow)

As useful as FTBUtils is with permissions, the fact they have almost zero documentation is extremely annoying, so at the bare minimum a better permissions plugin of some kind. Among other typical "Server Management" plugins like a sort of essentials, ect.

I realize there are forge mods that do some of these things, but as someone who ran a bukkit/spigot server back in the day, I feel the way these plugins are loaded makes the server admin job far easier. Honestly i could give a shit less what sponge adds in for "optimization, blah"

**Comment by FallenEagle1** [comment]
Then I guess the answer I would give is: `Spongeforge has been known to be able to be used on servers for Remix, but I wouln't add it unless you have specific plugins in mind.` There are a couple different sponge plugins that do work, and adding sponge later on isnt too hard from my understanding. The biggest thing I see is that spigot/bukkit plugins just don't work with spongeforge, so it just limits what can be used. There are some plugins that are useful and I can see them being used though. There just seems to be a couple bugs that like to show up as well when sponge is used, but that is typical of any mod that is added as well.

**Comment by KaneHart** [comment]
In a perfect world we really should encourage developers to consider supporting and porting their plugins into forge. So even if you need sponge for a plugin feel free to put a ticket in asking them to consider making a forge version in the future.

**Comment by Darkere** [comment]
Some Spongeforge bugs from memory: 
- Enderlilys are broken. not spawning in the end and not dropping from grass. 
- Woot boss shards are unobtainable.
- Broken spawners not dropping
- Some armor items don't give armor

These are the ones I ran into playing on a sponge server for about a week so there's probably way more to find.

**Comment by derrickmehaffy** [comment]
Good to know @Darkere that is what I was hoping to figure out.

**Comment by nathanjdarby** [comment]
What version of SpongeForge have you been using because I've been trying to install Sponge Onto the latest ATM3R server and it won't even successfully start up and ends up restarting. ?

**Comment by FallenEagle1** [comment]
For our official servers, we don't use sponge. Typically, anything that we want to do with the server we can do with mods, and sponge tends to add more headaches than what we consider worth the effort. Understandably, our plans for the servers vary from others, but we still try to point out the mods that can do similar aspects to what people usually want from sponge. Not everything exists in mod form, but some of it does in one way or another.
