### ISSUE TITLE
Immersive Engineering config suggestions

### ISSUE THREAD

**Issue by cmmgaming** [AllTheMods/ATM3-Remix#134]
# If this is enabled, wires connected to power sources will cause damage to entities touching them
    # This shouldn't cause significant lag but possibly will. If it does, please report it at https://github.com/BluSunrize/ImmersiveEngineering/issues unless there is a report of it already.
    B:enableWireDamage=true  <- due to how big this pack is...I'd turn it to false by default 

        # A whitelist of armor pieces to allow attaching the capacitor backpack, formatting: [mod id]:[item name]
        S:powerpack_whitelist <
         >

        # The base amount of Flux consumed per shot by the Railgun
        I:railgun_consumption=400

        # A modifier for the damage of all projectiles fired by the Railgun
        D:railgun_damage=3.0

        # A whitelist of foods allowed in the toolbox, formatting: [mod id]:[item name]
        S:toolbox_foods <
         >

        # A whitelist of tools allowed in the toolbox, formatting: [mod id]:[item name]
        S:toolbox_tools <
         >

        # A whitelist of wire-related items allowed in the toolbox, formatting: [mod id]:[item name]
        S:toolbox_wiring <
         >
<- also to enhance I'd also add more of the tools from other mods to accept the toolbox slots and other foods.

**Comment by FallenEagle1** [comment]
I'm not to worried about wires lagging, as it seems that they are not used as much, and when profiled they've never made a blip for causing extra processing to warrant anything. As for the toolbox, if the whitelist would accept just mod ids/names I'd consider it, but it does not look like it does. The lists would get very long, so I'm not to keen on going through all items to see what would deem being whitelisted.
