### ISSUE TITLE
Deuterium and Tritium type that can't be used in Nuclearcraft Reactors

### ISSUE THREAD

**Issue by FSDel** [AllTheMods/ATM3-Remix#135]
I harvested some Deuterium and Tritium from a Gas Giant ( "Fusionarium" )

These resources were different colours / types from the versions found in JEI. I can not find these ones in JEI at all, except in a clay bucket. 

These resources are able to be put into my RS system as a liquid. Unfortunately, these resources are not compatible with Nuclearcraft Fusion Reactors. ( I haven't tried Mekanism )

## Expected Behavior
Gases with the same name should work in all use cases

## Current Behavior
These types of resources do not work in Nuclearcraft

## Log
The planet settings from Planetdefs.xml

> 		<planet name="Fusionarium" DIMID="44">
> 			<isKnown>false</isKnown>
> 			<GasGiant>true</GasGiant>
> 			<gas>fluidtritium</gas>
> 			<gas>fluiddeuterium</gas>
> 			<gas>fluidhelium3</gas>
> 			<fogColor>1.0,1.0,1.0</fogColor>
> 			<skyColor>0.89,0.192,0.337</skyColor>
> 			<gravitationalMultiplier>200</gravitationalMultiplier>
> 			<orbitalDistance>130</orbitalDistance>
> 			<orbitalPhi>44</orbitalPhi>
> 			<rotationalPeriod>36000</rotationalPeriod>
> 			<atmosphereDensity>200</atmosphereDensity>
> 		</planet>
> 

![deuterium](https://user-images.githubusercontent.com/26369512/51440252-49bcab00-1d19-11e9-986c-3e6100231334.JPG)

![tritium](https://user-images.githubusercontent.com/26369512/51440257-550fd680-1d19-11e9-80c5-42e798e91260.JPG)

**Comment by Yoosk** [comment]
Gasses the mekanism use are not fluids. Mekanism has its own gas type that's not compatible with any other mod, only solution i could see would be to convert those fluid you have to mekanism ones.

**Comment by Darkere** [comment]
Mekanism unrelated.
There are multiple Deuterium/Tritium Fluids.
One from Nuclearcraft and One that he got from advanced rocketry. 
Would be nice if they were Oredicted although I don't know how easy that is to do.

Have been trying to get the fluid he has but it seems quite difficult.

**Comment by turbodiesel4598** [comment]
There is not really such a thing as 'ore-dicting' for fluids - this is just a case of that mod adding differently named fluids to the game which are not picked up on by NC, which currently looks for Mek's gases, Mek's `liquid` prefix for the fluid counterparts, or no prefix at all. That mod is adding a prefix of `fluid` and so is again an entirely different fluid.

This can be fixed easily on NC's side by just adding these fluids to the list of valid fusion fuels ;)
