### ISSUE TITLE
OpenComputers Robot flickering on robot.forward() movement

### ISSUE THREAD

**Issue by distunal** [AllTheMods/ATM3-Remix#136]
## Expected Behavior

The robot should be able to move forward without any flicker at all, blinking out of existence. But instead it blinks on movement.

https://gfycat.com/WeightyWealthyAnnelida

## Current Behavior

Robot blinks on movement while traveling to it's new location.

## Possible Solution

Could be a mod conflict? I made the same version of Minecraft and just put OpenComputers as the mod and I had no issues with movement.

## Steps to Reproduce

1. Make an OpenComputers Robot
2. give it the script: 
robot.forward()
robot.forward()
robot.turnLeft()
3. CTRL + S and then CTRL + W
4. type ./test.lua <- Or whatever you named it and then exit the robot and watch it move forward.

**Comment by Yoosk** [comment]
Tried to reproduce that in latest version of pack, 1.1.0 Remix, everything seems to behave as expected, robot it's not teleporting around. I would suggest to make sure you have latest java and optimized settings by following the guide:
https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/
