### ISSUE TITLE
Memory leak in the nether

### ISSUE THREAD

**Issue by firestronk** [AllTheMods/ATM3-Remix#137]
## Expected Behavior

Should be able to teleport to and from the nether with no problems

## Current Behavior

When entering the nether, ram usage increases slightly and chunk updates skyrocket to around 150+. Upon leaving the nether and entering the overworld, ram usage skyrockets and micro stuttering starts occurring every few seconds even when standing still.

## Steps to Reproduce

1. Enter nether
2. Enter overworld back through the nether portal
3. Lag and chill
4.

## Log

https://gist.github.com/firestronk/2ce87e1f6c12730f4147acfa704ec4a1

**Comment by Yoosk** [comment]
I would suggest to correct your java version (update it), grab new pack version and report if the issue persist.
