### ISSUE TITLE
Dank Null deleting contents when opened [1.0.3]

### ISSUE THREAD

**Issue by Yamza** [AllTheMods/ATM3-Remix#140]
Issue Report
https://github.com/p455w0rd/DankNull/issues/151
https://github.com/p455w0rd/DankNull/issues/156

Demonstration
https://i.imgur.com/3j0JnlU.gifv
https://i.imgur.com/ClXbVv3.gifv

Recommend reverting to previous version unless an update is released by next pack update.

**Comment by thehappybub** [comment]
Can confirm.
