### ISSUE TITLE
AgriCraft Crop Breeding Automation

### ISSUE THREAD

**Issue by thehappybub** [AllTheMods/ATM3-Remix#141]
The "Computer Controlled Seed Analyzer" from the AgriCraft mod does not function correctly in atm3 remix 1.03, making it a useless block. When attempting to wrap it as a peripheral in turtles or computers via a line in the CraftOS 1.8 similar to:

analyzer = peripheral.wrap("side")

the error program_name:line#: attempt to index global 'analyzer' (a nil value) is returned.

The problem could be a result of AgriCraft, some weird mod interaction, or some modpack settings … I have no clue. Either way, this can be worked around by integrating the mod _EnderIO Addons_ (https://minecraft.curseforge.com/projects/ender-io-addons?page=2) as that mod includes the "EnderIO Agricraft Farming Station" which would fulfill a similar function to the "Computer Controlled Seed Analyzer."

## Expected Behavior
When using the peripheral.wrap() command, a ComputerCraft (in this case CC: Tweaked) turtle or computer should be able to interact with a block it is able to interact with and make it do specified actions. The command should allow a turtle or computer to be programmed with commands specific to the analyzer and to make the seed analyzer perform a number of commands related to analyzing AgriCraft seeds.

## Current Behavior
The AgriCraft "Computer Controlled Seed Analyzer" is not recognized by CC: Tweaked computers and turtles as a wrap-able peripheral. 

## Possible Solution
(1) Checking the mod "CC: Tweaked" to see if it has some lost functionality from the original Computer Craft mod … this may well be the problem. It would be a shame that a Computer Craft fork with supposedly more functionality would have actually lost functionality.
(2) Adding the mod _EnderIO Addons_ (https://minecraft.curseforge.com/projects/ender-io-addons?page=2) to a future update of the pack.
(2) Updating the mods CC: Tweaked and AgriCraft to more current versions (?)
(3) Checking to see if there were any changes made to CC: Tweaked or AgriCraft config settings which might screw with it.
(4) Checking for any kind of itemID conflicts of the Computer Controlled Seed Analyzer

## Steps to Reproduce
1. Place down an AgriCraft "Computer Controlled Seed Analyzer"
2. Place down a CC: Tweaked "Advanced Computer" on top of the analyzer.
3. Open the gui of the Advanced Computer
4. type: "edit startup" and press ENTER
5. On the 1st line type: "analyzer = peripheral.wrap("bottom")"
6. On the second line type: "analyzer.analyze()"
7. Press CTRL and Save the program by hitting ENTER
8. Hold CTRL+R for 3 seconds
9. The computer will return red text saying: "startup.lua:2: attempt to index global 'analyzer' (a nil value)"

## Log
n/a

## Detailed Description
One of three things:
(1) Check with CC: Tweaked to see if there was any lost functionality. I will try to contact the devs of that mod and see if its a problem on their end. If they end up fixing it, update CC: Tweaked to the newest version, if its not them, seeing if there's anything in atm3-remix which might have screwed something up.
(2) Check to see if there are any item-specific conflicts with the "Computer Controlled Seed Analyzer"
(3) Add the mod EnderIO Addons to a future update of the atm3-remix mudpack to totally circumvent this issue.

Thanks for your time!

**Comment by thehappybub** [comment]
Nevermind the EnderIO Addons, I just noticed it was for 1.7 … unless someone can fiddle with the mod (which is open source) to make it compatible perhaps.

**Comment by Yoosk** [comment]
https://github.com/SquidDev-CC/CC-Tweaked/issues/110
Nothing i can do on pack level.
