### ISSUE TITLE
Jumping causes your connection to terminate

### ISSUE THREAD

**Issue by The-Educational** [AllTheMods/ATM3-Remix#143]
## Expected Behavior

Join server and when I jump i crash

## Current Behavior

jump = connection terminaion 

## Steps to Reproduce

1. join server
2. jump
3.game crash
4.

## Log

https://gist.github.com/The-Educational/ff944d0868ebf45f8fdf49dfea9d6dc2

## Detailed Description

removing mods?

**Comment by Yoosk** [comment]
It seems related to https://github.com/Vazkii/AutoRegLib/issues/11
Not something we can fix on pack level since you had to add some external mods.
