### ISSUE TITLE
Crash on loading Conjured Light Orbs

### ISSUE THREAD

**Issue by nowifi4u** [AllTheMods/ATM3-Remix#144]
TileConjured is crashing a Minecraft Server Instance on loading terrain with tile.conjured.name light orbs.

Issue report:
[Vazkii/Psi#481](https://github.com/Vazkii/Psi/issues/481#issue-408993462)

Crash log: 
[PASTEBIN (link)](https://pastebin.com/Tvr2ix5N)

Recommend updating the modpack as soon as this issue is fixed (it is in "awaiting merge" status right now), 10-20 crashes a day because someone tries to connect to the server is no good.

**Comment by Yamza** [comment]
Allocating more RAM may also help since your current allocation is being capped. 
`Memory: 5838777736 bytes (5568 MB) / 8353742848 bytes (7966 MB) up to 8353742848 bytes (7966 MB)`

**Comment by Yoosk** [comment]
Not something we can fix on pack level, but there are things you can improve regardless your java version and RAM allocation.
