### ISSUE TITLE
Cinnabar Ore Fortune = Infinite Redstone

### ISSUE THREAD

**Issue by MVethana** [AllTheMods/ATM3-Remix#149]
## Expected Behavior

Running Cinnabar Ore through a mechanical miner with fortune 3 should only yield the ore.

## Current Behavior

Running Cinnabar Ore through a mechanical miner with fortune 3 yields the ore and some red stone which can be reprocessed for infinite red stone with a mechanical miner and user setup.

## Steps to Reproduce

1. Cinnabar ore in a mechanical user in place mode
2. Mechanical miner with a fortune 3 book mines the ore and generates redstone.
3. Profit???

**Comment by Yoosk** [comment]
Seems that only happens with thaumcraft variation of cinnabar ore. So my solution will be to remove that from world gen, and leave only tech reborn cinnabar, which will be available only in nether, however numbers will be higher to compensate missing generation in overworld.
