### ISSUE TITLE
Manufactory from nuclearcraft crushes coal into ic2 coal dust which is annoying.

### ISSUE THREAD

**Issue by SubjectHawk66** [AllTheMods/ATM3-Remix#151]
## Expected Behavior
Thermal expansion pulverized coal should be the product

## Current Behavior
Crushed coal from ic2 is instead the product

## Possible Solution
Change the product.

## Steps to Reproduce
1. put coal in manufactory
2. profit

## Detailed Description
I was trying to make the capacitor from enderio and I figured this out. I feel like the recipe should also have ore dictionary for coal dust.

**Comment by turbodiesel4598** [comment]
Another, perhaps more general solution to issues like this could be solved by [enabling the ore dict priority list](https://github.com/AllTheMods/ATM3-Remix/blob/master/overrides/config/nuclearcraft.cfg#L931-L932) for NC machines?

**Comment by Yoosk** [comment]
Great suggestion, not sure how i missed that, thanks!
