### ISSUE TITLE
ET Ore Miner Tier 1 is digging up an invalid item

### ISSUE THREAD

**Issue by Halfdeaf** [AllTheMods/ATM3-Remix#152]
## Expected Behavior

Ore should not be able to be mined by Tier 1

## Current Behavior

Untextured Item,tile.draconicevolution:draconium_ore.name (#4572/32767), that when placed down turns into the correct block. See screenshot

## Steps to Reproduce

1.
![draconic ore issue](https://user-images.githubusercontent.com/48191482/53704868-2c9af200-3e18-11e9-85ee-0c26069c7512.png)

2.
3.
4.

**Comment by Boomflex** [comment]
This was an issue a long time ago but according to this thread it was fixed?

https://github.com/ValkyrieofNight/EnvironmentalTech/issues/103

Might be worth reposting this to the Environmental Tech dev.

**Comment by FallenEagle1** [comment]
Was supposed to be, but latest remix update (1.1.0) supposedly it is happening with the t1 void ore miner. Was talking about it some in discord.

**Comment by Boomflex** [comment]
I remember back on the ATM3 Server I had a RS setup for this block that would place and Fortune break it ha!

**Comment by Yoosk** [comment]
[There's no draconium ore in T1 void miner at all, in current versions of pack.](https://github.com/AllTheMods/ATM3-Remix/blob/dev/overrides/config/environmentaltech/multiblocks/void_miner/ore/tier_1.json) What version of pack are playing @Halfdeaf ?

**Comment by Boomflex** [comment]
Can confirm no Draconium Ore appears in the T1 void miner in v1.1.0.

**Comment by Halfdeaf** [comment]
This is indeed v1.1.0. I had already checked JEI and confirmed that Tier 2 was needed to for Drac Ore which led me to believe that this was more than a missing texture issue

**Comment by Boomflex** [comment]
@Halfdeaf Are you playing on a server?

**Comment by Yoosk** [comment]
As i said before, there's no draconium in T1 void ore miner, if checked that for few last hours. It has to be some issue on your side.

**Comment by Boomflex** [comment]
Ran T1 over night and all day and 0 broken Draconic ores.

Can confirm this was on the end of the user, not the pack.

**Comment by syndran** [comment]
This should not be closed. still an issue. 
Ore is produced by industrial forgoing Laser Base, not the void miner
ore is not textures, cannot be processed. placing in world fixes issue

**Comment by Yamza** [comment]
This will be resolved when the pack updates Draconic Evolution https://github.com/brandon3055/Draconic-Evolution/issues/1236
