### ISSUE TITLE
Updated, draconic ore as invalid item

### ISSUE THREAD

**Issue by syndran** [AllTheMods/ATM3-Remix#154]
reopen of issue
[closed issue] (https://github.com/AllTheMods/ATM3-Remix/issues/152#issue-416591554)

Updated. the source machine appears incorrect. 
Ore is produced by "industrialforgoing:laser_base"
not the environmental void ore miner. 

ore has no world property and no texture. cannot process. placing in over world fixes issue.

**Comment by Blueletric** [comment]
Separate issue, ET tier one miner was not supposed to have draconic ore. This not having a texture/world property is a mod interaction problem

**Comment by syndran** [comment]
issue only appears in TM3 remix. not in ATM3. this is a pack related issue.

**Comment by Yamza** [comment]
This will be resolved when the pack updates Draconic Evolution https://github.com/brandon3055/Draconic-Evolution/issues/1236
