### ISSUE TITLE
Server restart kills OpenComputer drives

### ISSUE THREAD

**Issue by syndran** [AllTheMods/ATM3-Remix#155]
When using OpenComputers with internal hard drives, with OpenOS installed. server restart causes the drives to "brick" and become invalid items with full data loss. 

## Expected Behaviour
on server reboot, interacting with a filesystem would result in normal behaviour. 

## Current Behaviour
any computer that was running a script on server restart will continue to run as normal until it is restarted, or execution is interrupted.

Any computer left at command prompt will return no result to an "ls" command. and restarting will cause unrecoverable error on the PC. 

## Steps to Reproduce

UNABLE TO REPRODUCE WITH 
-         MC and OpenComputer
-         ATM3 5.11.2
-         FTB Revelation

REPRODUCIBLE WITH
-       ATM3 - remix 1.1.0   
(reproduced on 3 separate servers by multiple people)

working before reboot. 
![prereboot](https://user-images.githubusercontent.com/47623906/54080470-2509aa80-433c-11e9-9526-7ad5851aac2b.png)

after server reboot, all commands  provide no response
![postreboot](https://user-images.githubusercontent.com/47623906/54080479-75810800-433c-11e9-8c90-02da73d4aa2a.png)

restarting the opencomputer causes bluescreen
![restartedPC](https://user-images.githubusercontent.com/47623906/54080481-80d43380-433c-11e9-893c-6715798e142a.png)

**Comment by Yamza** [comment]
Wasn't able to reproduce the issue on Remix 1.1.0 using the official server.

**Comment by PotDucky** [comment]
Resolved. ended up being a server specific issue.
