### ISSUE TITLE
[1.1.0 & 1.1.1] Refined Storage disks losing contents

### ISSUE THREAD

**Issue by Yamza** [AllTheMods/ATM3-Remix#159]
Refined Storage seems to lose it's disk data randomly.

## Current Behavior
When accessing the crafting grid, items will not be shown, or not be accessible.

## Possible Solution
Remove drives and replace, if that does not work...
Restore RS data from backup

## Steps to Reproduce
Unknown at this time

https://github.com/raoulvdberge/refinedstorage/issues/2190
https://github.com/raoulvdberge/refinedstorage/issues/2140

**Comment by Yoosk** [comment]
I would suggest to change `B:skullStackingFix=true` to `B:skullStackingFix=false` in `randompatches.cfg` and report back if it's better. It certainly does help for 1.1.1 silent crashes and logs spam.
