### ISSUE TITLE
Copper Ore(Project Red) not compatible with Mekanism

### ISSUE THREAD

**Issue by SneakyDevil** [AllTheMods/ATM3-Remix#161]
Copper Ore is uniquely using the ProjectRed variant making it the only ore variant that does not work with the mekanism ore multiplier.

## Expected Behavior
Ore being able to be run through the system

## Current Behavior
Or has no recipes to be run with the ore multiplier

## Possible Solution
Change the ore to any other variant or add the recipe for ProjectRed ores

Note: this is using the most current Beta version.

**Comment by FallenEagle1** [comment]
How did you get the projectRed version in the first place?

**Comment by SneakyDevil** [comment]
By mining it

**Comment by FallenEagle1** [comment]
So another issue in this as well. Only thermal should be spawning in world.

**Comment by SneakyDevil** [comment]
Hum, on double checking I have  a stack of thermal copper as well

**Comment by Yoosk** [comment]
Checked fresh 1.1.1 modpack version, default generation (BoP) doesn't yield any copper ore beside one from Thermal Expansion.

**Comment by SneakyDevil** [comment]
I guess I'm just magical like that then
