### ISSUE TITLE
Mixed Metal Ingots and Iridium Ore do not convert

### ISSUE THREAD

**Issue by pyr02k1** [AllTheMods/ATM3-Remix#163]
When gathering from Dungeons, provided Iridium is IC2, provided Mixed Metal Ingots are Tech Reborn. TR MMI do not have any method of converting to IC2 MMI. IC2 MMI can be crafted fine via plates. 
Mined Iridium also does not convert to IC2 Iridium. 

## Expected Behavior
MMI and Iridium should have a oredict across both IC2 and TR to allow for use in all recipes

## Current Behavior
Neither convert between mods making some recipes excessively difficult. Iridium plates for example would require a ton of MMI creation (which is fine and expected) but also require a ton of dungeon searching to find IC2 iridium.

## Possible Solution
Oredict MMI and Iridium.

## Steps to Reproduce
1. MMI - Log in, locate MMI in a dungeon chest, note that it is unusable. 
2. Iridium - Log in, mine Iridium, note that it doesn't convert to IC2 Iridium

**Comment by FallenEagle1** [comment]
Mixed metal ingots can be looked into, that shouldn't be an issue. However, for the iridium that is specifically intended. We didn't change it, that's the way it came, but dont have plans to oredict either. The ic2 ore is intended to be hard to find, it's for end game materials in that mod. The intended route for that is find one, then replicate it using uu matter.

**Comment by pyr02k1** [comment]
Makes sense. Appreciate the Mixed Metal Ingots at the least. Not a big deal to make them, but sitting on half a stack of the incorrect mod version can be a bit annoying. 

Thanks,
John
