### ISSUE TITLE
Unable to craft Energy Flow Circuit (Tech Reborn)

### ISSUE THREAD

**Issue by DKnightADRI** [AllTheMods/ATM3-Remix#166]
Literally the title. (I shiftclicked the recipe just in case)
https://imgur.com/a/7kfm9Cv

## Expected Behavior
It should return 4 Energy Flow Circuits per crafting operation.

## Current Behavior
No crafting result.

## Possible Solution
Crafttweaker maybe?

## Steps to Reproduce
Attempt to craft the item.

**Comment by FallenEagle1** [comment]
More info would be good. Is this on a server? If so, does it work in singleplayer? What version of the modpack? Are there any modifications to the modpack at all?

**Comment by DKnightADRI** [comment]
This was on Singleplayer, version All the Mods 3 - Remix 1.2.0 (updated today). No modifications were made except a texture pack.

**Comment by Yoosk** [comment]
Works perfectly fine for me, tested any of possible item matches from ic2 and tr. Might be due to mod updates that i already have on my dev instance.
