### ISSUE TITLE
Recipe Conflict Silicon/fused Glass

### ISSUE THREAD

**Issue by Ghromm1201** [AllTheMods/ATM3-Remix#171]
By smelting Nether Quartz in an alloy smelter i get Silicon
smelting to fused Glass is not possible

## Expected Behavior
1 Quartz should give SIlicon
4 Quartz should give fused glass

## Current Behavior
always smelts Quartz to Silicon

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Yamza** [comment]
Did you set the alloy smelter to alloy mode?

**Comment by Ghromm1201** [comment]
Okay that fixed the Problem. Thought i did that before. My fault

Gesendet von Mail für Windows 10

Von: Yamza
Gesendet: Mittwoch, 17. April 2019 20:54
An: AllTheMods/ATM3-Remix
Cc: Ghromm1201; Author
Betreff: Re: [AllTheMods/ATM3-Remix] Recipe Conflict Silicon/fused Glass(#171)

Did you set the alloy smelter to alloy mode?
