### ISSUE TITLE
Crash when picking up EnderIO Transceiver while wearing Botania Ring of Magnetization

### ISSUE THREAD

**Issue by Unsinge** [AllTheMods/ATM3-Remix#173]
## Expected Behavior

Breaking the Dimensional Transceiver block should allow you to pick it up, even if you are wearing the Botania Ring of Greater Magnetization. 

## Current Behavior

The game crashes with a user issue, and the block never makes it to your inventory.

## Possible Solution

If I use magnets from other mods, there is no problem. And the Botania ring seems to work fine with everything else - been wearing it for weeks without issue, but just started using the Dimensional Transceiver.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by FallenEagle1** [comment]
Do you have a crash report? Can't really do anything without one.

**Comment by Yoosk** [comment]
Tested what i possibly could in upcoming dev version, without issues.
