### ISSUE TITLE
Extreme Reactors 

### ISSUE THREAD

**Issue by ETERN4LVOID** [AllTheMods/ATM3-Remix#174]
There appears to be numerous problems with the fuels for extreme reactors, yellorite ingots do not exist, when you smelt the ore you get no item, and any other fuel such as refined uranium cannot be acquired properly. Smelting uranium give no item at all. I also changed the recipes to simplified and doing that makes the reactor controller impossible to craft. Items from the mod are certainly missing or are not integrated properly.

To see the issues just use JEI to see the recipes of Extreme reactors and from that you can see there are some problems. The main one being that the is not craftable fuel and some of the recipes are not possible to craft.

Another issue being the molten enderium which is a coolant for the mods is untextured, I tried it with a resource pack and with out.

**Comment by FallenEagle1** [comment]
I would start with a reinstall, as I haven't seen these issues to start with. I can double check again this afternoon, but last I saw they were working. Also, what version of the modpack?

**Comment by ETERN4LVOID** [comment]
> I would start with a reinstall, as I haven't seen these issues to start with. I can double check again this afternoon, but last I saw they were working. Also, what version of the modpack?

I have reinstalled the modpack and it has solved some issues. It appears that when I changed the recipes in the config from normal to simplified it does cause some issues but reinstalling changed all of that back. Refined uranium can now be acquired. But im still rather confused why yellorite doesn't exist the ingots are not in JEI but the ore is. 
Also molten enderium is still untextured it is like a bright pink liquid that set me on fire. I think I initially confused this with resonant ender but molten enderium still shouldn't behave like that.

I think the major issues when the recipes are changed in the config. But even without them being changed yellorite ingots cannot be acquired, Im not sure if this is intented or not as it is the base mod fuel and crafting item.

**Comment by FallenEagle1** [comment]
Yellorium shouldn't be able to acquire, as it is oredict with uranium and uranium is the intended fuel use. That and blutonium.

**Comment by ETERN4LVOID** [comment]
> Yellorium shouldn't be able to acquire, as it is oredict with uranium and uranium is the intended fuel use. That and blutonium.

Oh right I see, I wasn't aware of that. All other modpacks I've played have had yellorite ingots so I was a bit confused.
Thanks for pointing that out.

**Comment by Sleeeper** [comment]
btw yellorium ore comes along with uranium ore in void ore miner (tier 6 at least). no big deal, can convert it all to uranium with crafting
