### ISSUE TITLE
Waterstrainer Recipe conflict

### ISSUE THREAD

**Issue by FallenEagle1** [AllTheMods/ATM3-Remix#175]
Probably affects remix, definitely affects atm3. The first level of water strainer has a recipe conflict.

**Comment by Yoosk** [comment]
Would love to know which exact item conflicts, can't find anything like that

**Comment by FallenEagle1** [comment]
Yep, sorry. I think it got resolved later in discord and I forgot to update this. It was the net itself, but both packs are good.
