### ISSUE TITLE
IE Cloche Compat does not allow T6 Mystical agraddition seeds

### ISSUE THREAD

**Issue by iiixi** [AllTheMods/ATM3-Remix#176]
In atm3r V1.2, "MystAgrad Cloche Compat" mod was included which allowed using Mystical agradditions seeds into Immersive Engineering Garden cloches. This was done by placing the respective crux in the soil slot.

In V1.3, this mod was replaced with "IE Cloche compat". T6 seeds (Nether start seed, Dragon egg seed, Awakened draconium seeds and inferium seed) can no longer be placed in cloches. It looks like the mod is configured correctly to allow growing T6 seeds.

Suggest switching back to "MystAgrad Cloche compat" as "IE Cloche compat" hasn't been updated in a while and other users are reporting similar issues: https://github.com/NicJames2378/IEClocheCompat/issues/10

**Comment by kkjdroid** [comment]
IE Cloche Compat is by the same author as the previous mod, and the creator considers it to be a successor. I don't think that the first mod will be updated further, whereas hopefully the new one will. That said, I'm having the same issue, so it may be wise to roll it back until the bug is fixed.

**Comment by Yoosk** [comment]
Downgrading to old version of new compat fixes the issue for now.
