### ISSUE TITLE
crash on scrolling hotbar( i think)¯\_(ツ)_/¯?

### ISSUE THREAD

**Issue by V0odoofyxen** [AllTheMods/ATM3-Remix#179]
## Expected Behavior
use of builders wand to fill in area with stone for miniralis ritual.

## Current Behavior
just finished excavating the ores from under a miniralis ritual in a cube, had just put stacks of stone in inventory and a diamond building wand on my hot bar, activated jetpack and right clicked on the stone below me to fill in the area under the ritual when the screen froze and the screen changed color(not the usual white crash screen). i could still hear the jetpack while the screen was frozen before it crashed completely. thought the wand was to blame and was going to use mcedit to deletit but got back into my world and managed to put it in to the trash, went to continue on and used my mose wheel to scroll along my hot bar and crashed again.  

loading into the world seems fine and i've moved about and open inventory and moved things about but as soon as i use my mouse wheel to scroll my hotbar it and it hit slot 5/6/7 it crashes. 

## Steps to Reproduce
1.
2.
3.
4.

## Log
 i ended up with multiple tabs open on pastebin so i'm not sure if 3 and 4 are the same crash log.
crash log 1 -  https://pastebin.com/uJfgLAfX
crash log 2 - https://pastebin.com/KnYPxLSu
crash log 3 - https://pastebin.com/h0S8UepP
crash log 4 - https://pastebin.com/7cKKNwd8

**Comment by Yamza** [comment]
Mod issue. No fix. https://github.com/portablejim/BetterBuildersWands/issues/105
