### ISSUE TITLE
Mystical Agg Farming

### ISSUE THREAD

**Issue by Chocopuffs** [AllTheMods/ATM3-Remix#18]
You can't right click to harvest a seed, you have to break it to harvest, then re plant the seed.

## Expected Behavior
Right click to harvest

## Current Behavior
Left click, break, replant

## Possible Solution
Cyclic harvester picks them normally for me.

## Steps to Reproduce
step 1: plant seed
step 2: grow seed
step 3: try and right click

**Comment by FallenEagle1** [comment]
Is this specific seeds, or all of them?

**Comment by Chocopuffs** [comment]
all but inferium which makes me think it may be to do with the agricraft disable
