### ISSUE TITLE
Nuclearcraft Lithium dust cannot be smelted by Mekanica energized smelter

### ISSUE THREAD

**Issue by Beablebeable** [AllTheMods/ATM3-Remix#180]
## Expected Behavior
Lithium Ore should be able to be tripled in the Mekanica ore tripling process like the other three Nuclearcraft ores.  Lithium dust can be smelted in other smelters.

## Current Behavior
Lithium is processed all the way to the "dust" phase of the process, but then cannot be smelted in the Energized Smelter.

## Steps to Reproduce

1. Set up Mekanica ore tripling Tier 2 as described here: https://wiki.aidancbrady.com/wiki/Ore_Processing
2. Observe that Thorium, Boron, and Magnesium are tripled correctly and end up as ingots.
3. Observe that Lithium stops at the dust phase.
4.

**Comment by kkjdroid** [comment]
Lithium dust also can't be smelted by the EnderIO Alloy Smelter. It does work in the Tinker's Construct Smeltery, however.
