### ISSUE TITLE
Project red tin ore incompatible with Mekanica purification chamber

### ISSUE THREAD

**Issue by CalamityKing** [AllTheMods/ATM3-Remix#182]
Project red tin incompatible with Mekanica Purification Chamber

The project red tin isn't processed.

## Possible Solution

There doesn't seem to be a recipe for converting the project red tin into a tin clump
in the game.

## Steps to Reproduce

1. Attempt to place the project red tin into the purification chamber
2. Observe that it the machine doesn't start to turn it into tin clumps

**Comment by CalamityKing** [comment]
As I saw that apparently project red copper isn't supposed to be present in a world according to another post, I'll note that while I don't exactly remember where I mined it from it was likely from the mining dimension.

**Comment by FallenEagle1** [comment]
It shouldn't be able to be mined up, it shouldn't be able to spawn. Can you figure out how you got it in the first place so that can be fixed?

**Comment by kkjdroid** [comment]
The underground Astral Sorcery rooms with the respawning ore in the center can have ores that are otherwise disabled, and loot chests sometimes have disabled ores.

**Comment by Yoosk** [comment]
I'm afraid i can't specify which exact ore from oredictionary can spawn in Astral Sorcery. However i might be able to tweak chest loot.

**Comment by CalamityKing** [comment]
It was most likely the Astral Sorcery room that I obtained it from, but at least you got something out of the report.

**Comment by FallenEagle1** [comment]
There is also a crafting recipe already of two ores (any mod type) to create 2 of the same ore, but be the thermal expansion variant.
