### ISSUE TITLE
Unable to add radiation shielding to Simply Jetpacks

### ISSUE THREAD

**Issue by msgerbs** [AllTheMods/ATM3-Remix#186]
I am unable to add Radiation Shielding from Nuclearcraft to Simply Jetpacks. In JEI, all the recipes for Jetpack + Radiation Shielding show it makes a creative jetpack, and attempting to craft it simply doesn't act as a valid recipe. Armor or no armor, charged or empty, it makes no difference.

## Expected Behavior
I should be able to add radiation shielding to a jetpack.

## Current Behavior
I am unable to do so, the crafting recipe doesn't appear to be valid.

## Steps to Reproduce

1. Craft any Simply Jetpacks... Jetpack.
2. Craft any Nuclearcraft Radiation Shielding
3. Attempt to craft the 2 items together
4. Nothing happens

**Comment by FallenEagle1** [comment]
What modpack version? I just tested this, and while the jei recipe shows the creative jetpack (for whatever reason, looking into it) I was able to craft the plating with any jetpack just fine.

**Comment by FallenEagle1** [comment]
Also, what crafting table(s) have you tried using?

**Comment by msgerbs** [comment]
I just tried a regular crafting table. We are running 1.3.0.

**Comment by msgerbs** [comment]
https://i.imgur.com/uOwcWT1.png

**Comment by FallenEagle1** [comment]
It looks like enchants are the issue. I'm able to craft it just fine if there are no enchants on the item, but if there are it will not work. Incidentally, this seems to happen only with simply jetpacks, so I'll look into opening a github issue on it to get it resolved. Will probably have to open a separate github issue dealing with it showing the crafting of the creative jetpack.

**Comment by msgerbs** [comment]
Thanks! I forgot to mention it was enchanted, but as you said normally that works fine. I guess for now I'll just disenchant it first.

**Comment by msgerbs** [comment]
I disenchanted the jetpack and even tried removing the armor just to make sure and I still couldn't add the rad plating. Was yours brand new when you tried it?

**Comment by FallenEagle1** [comment]
It was. Im guessing at that point it is an nbt issue
