### ISSUE TITLE
Mekanism Autocrafting Causes Heavy Lag

### ISSUE THREAD

**Issue by AlexHoff97** [AllTheMods/ATM3-Remix#188]
Autocrafting mekanism with AE2 causes many warnings in console and drops TPS heavily.

## Expected Behavior

Autocrafting to work properly

## Current Behavior

Running mekanism autocrafting gives errors like the following: 
https://pastebin.com/pVxrLYMx
This seems like a simular problem enigmatica has:  https://github.com/NillerMedDild/Enigmatica2Expert/issues/674

## Steps to Reproduce

1. Create Autocrafting recipes for example setup to make an ultimate energy cube
2. Start Autocrafting
3. Watch Console

## Log

https://pastebin.com/pVxrLYMx

**Comment by FallenEagle1** [comment]
It is a known problem dealing with autocrafting with energy tablets. Probably just going to have to manually craft that item, as the dev knows about it, and there isn't really anything we can do about it in the mean time. Might be that a mek update in the future will fix it, but I don't know what the devs have planned for fixes
