### ISSUE TITLE
Got crash on searching uses of UU-matter

### ISSUE THREAD

**Issue by Dourmouki** [AllTheMods/ATM3-Remix#189]
## Expected Behavior
i was looking JEi to see what UU-matter is used for

## Current Behavior
There was a Carpenter tab for UU-matter 

## Steps to Reproduce

1.search UU-matter at JEI
2.change to Carpenter tab
3.
4.

## Log
Ihttps://pastebin.com/5bWLjtEs

**Comment by SpeedSlider** [comment]
Based upon a quick review of this issue your Java version is listed as 1.8.0.51 which I think is the default bundled with twitch. You should update your Java to the latest 1.8 version; make sure not to go to 1.9 as testing is showing issues with this. You can reply here to let me know if that resolves your issue.

**Comment by SpeedSlider** [comment]
Reviewed this issue again. Searching uu-matter in version 1.3.2 only brings up a crafting tab and a fractioning still tab. This issue is resolved in the latest pack update.
