### ISSUE TITLE
Creating a SuperFlat World with the preset "The Void" crash the game and corrupt the save!

### ISSUE THREAD

**Issue by ReiDaTecnologia** [AllTheMods/ATM3-Remix#19]
## Expected Behavior

Create the world and use it to test stuff

## Current Behavior

The Game crash with error: java.lang.IllegalArgumentException: bound must be positive

## Possible Solution

The game crash because the Speleothem try to generate below the platform (That is -1) and this is impossible to happen then make the game crash. It's already fixed in the version of Quark (r1.5-128).

## Steps to Reproduce

1. Create a new world
2. Select "SuperFlat" as the worldgen type
3. Click in the "customise" 
4. Select the preset "The Void"
5. Click in Create World to him crash and corrupt.

## Log

https://gist.github.com/ReiDaTecnologia/cc22a010d5f97f0e0fb216f630da3797

## Detailed Description

Looks like various modpacks didn't know this issue and various players don't do a testing world like me and cause to nobody report this issue to various modpacks. I already reported this issue to another modpack:
https://github.com/NillerMedDild/Enigmatica2/issues/81
And also this is the issue in the mod repository that i found while searching about a fix:
https://github.com/Vazkii/Quark/issues/961
I hope you fix it 😃

**Comment by Yoosk** [comment]
Fixed with mod update.
