### ISSUE TITLE
Well of suffering in blood magic

### ISSUE THREAD

**Issue by ThePoonanna** [AllTheMods/ATM3-Remix#191]
So as in the tittle the well of suffering does take blood from the blood network but as it stands no mods of any kind take bleeding damage. Ive followed the instructions in the book about placement but when I activate it with that crystal both weak and awewaken crystal, nothing. Im not even sure whats messing with it to make it do that.

**Comment by FallenEagle1** [comment]
You might need to set up the area that the ritual looks for mobs from. The ritual tinker item is used for this. You can tell it what area to look for mobs, and it can be used on most rituals for various things.

**Comment by ThePoonanna** [comment]
I have fitled with that tool. Ive set the before and after activation with no luck.

**Comment by EnderProjects** [comment]
I use blood magic very often as its my favorite mod. this ritual does have other requirements for it to work like needing to be in the area of the blood alter. I don't know what your set up is so I cant really find out any "user made" errors

**Comment by ThePoonanna** [comment]
the mater ritual is under and 2 blocks away from it where it is sorta in the alter structure while still being able to still be fully constructed.

**Comment by ThePoonanna** [comment]
> I use blood magic very often as its my favorite mod. this ritual does have other requirements for it to work like needing to be in the area of the blood alter. I don't know what your set up is so I cant really find out any "user made" errors

How many tiers does the alter have?
