### ISSUE TITLE
Fertile Soil doesn't support all crops

### ISSUE THREAD

**Issue by Milavoldtofte** [AllTheMods/ATM3-Remix#192]
Fertile Soil, from Rustic, doesn't support all crops.

## Expected Behavior
Fertile Soil should be able to grow any crop that can grow on farmland.

## Current Behavior
Several crops from mods, such as XL Food Mod, can't be planted on fertile soil. Others do fine, like tomatoes from Rustic, Industrial Hemp, and vanilla crops.

## Steps to Reproduce

1. Make fertile soil (dirt + bone meal)
2. Put it down
3. Attempt to plant seeds from XL Food Mod on it
4. Nothing happens

## Detailed Description
Fertile soil provides a very aesthetic and practical option for farming, since you won't need to have water blocks in your fields or worry about trampling. At the moment though, I'm not sure if I should just go back to vanilla farmland until this is fixed. Ender lilies also don't seem to be able to grow on fertile soil, even though they can grow on grass, and I had them on fertile soil on an old ATM3 server. The integration of Cooking for Blockheads is also a bit lacking, but that's for another issue report. Pam's Harvestcraft is greatly missed.

**Comment by FallenEagle1** [comment]
This can be looked into some, but I'm pretty sure there is not anything we can do about this at the pack level. Unless there is some functionality I missed on it, the compatibility needs to be programmed in by the dev themselves, so not something we can change.
