### ISSUE TITLE
[Enhancement] Increase OpenBlock Elevator range to 12 

### ISSUE THREAD

**Issue by lanceweber** [AllTheMods/ATM3-Remix#193]
I'd like to suggest increasing the _searchDistance_ of the OpenBlock Elevator from 8 to 12 since _maxPassThrough_ is already set to 12. Given the increased emphasis on vertical vs horizontal builds, 12 blocks should easily accommodate taller room sizes without requiring the negative aesthetics associated with intermediary elevator blocks.

**Current**
```
config/openblock.cfg
dropblock {
...
 # The maximum amount of blocks the elevator can pass through before the teleport fails
    I:maxPassThrough=12
   ...
  # The range of the drop block
    I:searchDistance=8
...
}

```

**Suggested**
```
  # The range of the drop block
    I:searchDistance=12

```

**Comment by Darkere** [comment]
https://github.com/AllTheMods/ATM3-Remix/blob/dev/overrides/config/openblocks.cfg

already done in dev
