### ISSUE TITLE
Wrong case in enderio config file

### ISSUE THREAD

**Issue by Lartza** [AllTheMods/ATM3-Remix#196]
On Linux EnderIO generates a new enderio.cfg file due to case sensitivity, since the pack ships an EnderIO.cfg file

## Expected Behavior
Server/Client uses pack config

## Current Behavior
Minecraft generates a fresh enderio config

## Possible Solution
Rename the pack config file to enderio.cfg

## Steps to Reproduce
1. Download server/client
2. Run it
3. EnderIO creates a new config

I'm not sure exactly what case Windows uses when it creates the file and if it's an issue due to that or because it used to be EnderIO.cfg in the past, but Windows should be able to use either since it doesn't care.

**Comment by FallenEagle1** [comment]
Will say, it is in windows that things are being made and tested in, but the weird thing about this is that the files are newly generated most updates, and the one generated by the mod is EnderIO (with the case) will have to dig deeper into it, as I believe there are a couple other mods that do this too. They might be atm3 specific though.
