### ISSUE TITLE
Precision Sawmill does not acccept torches via automated input

### ISSUE THREAD

**Issue by The--Captain** [AllTheMods/ATM3-Remix#197]
## Expected Behavior
Precision Sawmill (Mekanica) should accept 4 torches to yield 1 coal and 1 stick.  It currently works using manual input, but not automated input.  All other items (that I have tested) are accepted via automated input.

## Current Behavior
Torches are not pulled into the processing inventory of the Precision Sawmill in an automated configuration, while all other items (that I have tested) behave as expected in the same automated configuration.

## Possible Solution
Perhaps change back to Mekanism?  

## Steps to Reproduce

1.  Use any method to attempt to feed torches into the Precision Sawmill other than by hand.
2. Headdesk

## Detailed Description
Include a version of Mekanica or Mekanism that does not exhibit this bug

**Comment by Yoosk** [comment]
What version of pack do you use? Because with 1.3.1 we included latest available version of mekanism.

**Comment by The--Captain** [comment]
I  checked the mod files on my computer, and of course you are correct - Mekanism (not Mekanica) mod files are the ones that are present.

So I guess I should add there's another bug where the in-game modlist and also the mod origin text (I think JEI is showing me this?) underneath the Mekanism mod items say "Mekanica" rather than "Mekanism", for some reason, which is why I originally reported the wrong mod.

Regardless, the Precision Sawmill is bugged.

I'm running ATM 1.3.0 (separate client and server machines, to reduce load).

**Comment by The--Captain** [comment]
Tested with ATM Remix 1.3.1 (Mekanism instead of Mekanica).  The same behavior (bug) is present.

The Precision Sawmill is definitely bugged in ATM Remix.  I will test a custom configuration that includes only Mekanism (and nothing else) to confirm a bug in Mekanism, or a mod conflict glitch.

**Comment by FallenEagle1** [comment]
Just did some testing with this. While it is a bug, it is a mod specific bug and not a modpack bug. This will have to be reported to the mekanism devs.
