### ISSUE TITLE
WorldEdit compass implemention borks Actually Additions

### ISSUE THREAD

**Issue by The--Captain** [AllTheMods/ATM3-Remix#198]
Clicking on any type of Actually Additions  laser relay while holding the compass should adjust the configuration of the Actually Additions laser relay, but instead teleports the user (i.e. WorldEdit compass implemention overrides)

## Expected Behavior
Right-cicking the compass should edit the configuration of Actually Additions relays.

## Current Behavior
Right-clicking the compass teleports the user; apparently WorldEdit is responsible.

## Steps to Reproduce

1. Try to use the compass to adjust the configuration of Actually Additions relays
2.  Teleport instead.
3.  Drown in lava
4. Or suffocate in a wall

**Comment by The--Captain** [comment]
Thanks for the impending fix, although I am admittedly immensely curious how the compass will be made to play nice with both WorldEdit and Actually Additions simultaneously - I can think of a few ways, and just wondering how it's going to play out.

**Comment by Darkere** [comment]
World edit now uses a Clock instead of compass.
