### ISSUE TITLE
Can't Craft Creative Builder's Wand

### ISSUE THREAD

**Issue by maddeath** [AllTheMods/ATM3-Remix#199]
## Expected Behavior
Should be able to craft an ATM Star, Builder's Wand, and Unbreakable Wand into a Creative Builder's Wand

## Current Behavior
None of the Unbreakable Wands count for the recipe.

## Steps to Reproduce
![image](https://user-images.githubusercontent.com/17349164/59234347-43807b80-8ba1-11e9-9bbf-e9426315d4e6.png)

**Comment by FallenEagle1** [comment]
This is in 1.3.0 for future reference
