### ISSUE TITLE
TE Pulverizer grinds RFTools Dimensional Shard Ore into NC Dimensional Blend

### ISSUE THREAD

**Issue by incendium** [AllTheMods/ATM3-Remix#202]
## Expected Behavior

TE Pulverizer should grind RFTools Dimensional Shard ore into RFTools Dimensional Shards

## Current Behavior

TE Pulverizer grinds RFTools Dimensional Shard Ore into NC Dimensional Blend

## Possible Solution

TE Pulverizer should grind RFTools Dimensional Shard Ore into RFTools Dimensional Shards

## Steps to Reproduce

1.  Put Dimensional Shard Ore into TE Pulverizer
2.  Receive NC Dimensional Blend

**Comment by FallenEagle1** [comment]
Going to leave this one as is for the moment. There are still ways to get the rftools dimensional shards, and to get a solid fix in place will mean rewriting a large number of recipes so that both of these work properly with all machines
