### ISSUE TITLE
Server crash just exploring

### ISSUE THREAD

**Issue by dantheman4700** [AllTheMods/ATM3-Remix#203]
crash report: https://gist.github.com/dantheman4700/6b7c38ad0e7e2c43bfe8b1d796ae27b6
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Lartza** [comment]
It's lagging to death due to world gen. Add a zero to max-tick-time in server.properties, pregenerate the world (https://minecraft.curseforge.com/projects/chunkpregenerator), explore slower, get a more powerful server.
