### ISSUE TITLE
Disable 3rd person switch during flight by default

### ISSUE THREAD

**Issue by scorpion451** [AllTheMods/ATM3-Remix#205]
## Expected Behavior
The camera not to change out of POV while flying

## Current Behavior
A mod is automatically changing the POV to 3rd person while flying, thus making me sea-sick and impeding my ability to avoid trees, cliffs, the ground, etc.

## Possible Solution
Have this option turned off by default in the configs, or at least have an easier means of tracking the setting down. (Even a mention in the FAQ would be nice) 

## Steps to Reproduce
1. Start minecraft after new update
2. attempt to fly
3. be disoriented by camera switching into 3rd person
4. fly into obstacle
5. spend half an hour trying to remember which mod was doing that and where in the configs you go to turn it off again before giving up and making issue ticket

## Detailed Description
I get that some people like this option, and have no issue with the feature's existence- but it's essentially a game-breaking bug for me.

**Comment by Lartza** [comment]
Isn't this only with the elytra? Not the conventional ways of flight (Jetpacks, rings, glider, armor)? I personally like third person on the elytra, but never use it in modded so wouldn't mind if it didn't default to third person.

**Comment by scorpion451** [comment]
I'm noticing it on Astral Sorcery's Mantle of the Stars attuned to Vicio, which mimics an elytra. I haven't progressed far enough in this world to mess with other forms of flight thus far. 

Still can't remember what mod does this- finally just broke down and copy-pasted the configs from my previous build to make it stop again- so I can't turn it back on to check . (I vaguely remember thinking it was a very random thing for the mod to do, like it was part of an agriculture mod or something equally unrelated.)

**Comment by FallenEagle1** [comment]
Random Tweaks is the mod that does this. It probably should be switched, as most people seem to dislike it, rather than like it. Boats will do this as well.

**Comment by Yamza** [comment]
Fixed in dev with https://github.com/AllTheMods/ATM3-Remix/pull/212/commits/9ef190962484270a55ef209d5bf3021c56bd7710
