### ISSUE TITLE
Two different world gen of oil that are incompatible

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Remix#207]
## Expected Behavior

When using the ranged pump to collect oil in an area all the oil should go into a drum.

## Current Behavior

Two different types of oil can spawn close to each other, perhaps in the same pool, but not clear based upon the player report from server. This will cause the ranged pump to stop since the container will have one type of oil and the pump will fill with another. The two types are immersive petroleum and tech reborn.

## Possible Solution

either ore dict the oils so they can be converted into the same container or remove one from world gen.

## Steps to Reproduce

1. setup ranged pump close to two different oil pools or a single one with two different types within.
2. try to pump into a container.
3.
4.

## Log

N/A

## Detailed Description

As described above.

**Comment by Yamza** [comment]
Immersive Petroleum: https://i.imgur.com/AcTugRQ.png
Tech Reborn Oil: https://i.imgur.com/uu4Oc1p.png
