### ISSUE TITLE
Minecolonies children do not grow up

### ISSUE THREAD

**Issue by lhw** [AllTheMods/ATM3-Remix#208]
Currently due to a known bug ldtteam/minecolonies#3600 the minecolonies children do not grow up ever.

## Expected Behavior
They do

## Current Behavior
They don't

## Possible Solution
Update to a newer version of minecolones with the merged change

## Steps to Reproduce

1. Build citizen hall/house in creative
2. Have a few kids spawn
3. Wait forever

## Log

/

## Detailed Description

/

**Comment by FallenEagle1** [comment]
When the modpack updates, we update every mod to the latest unless we find an issue with it. Will update minecolonies when the pack get updated.

**Comment by lhw** [comment]
Cool. That takes care of that.
