### ISSUE TITLE
Minecolonies doesn't spawn in new villagers when the barracks are built or town hall is upgraded

### ISSUE THREAD

**Issue by 2Dewds** [AllTheMods/ATM3-Remix#209]
## Expected Behavior

When the barracks are built or when the town hall is upgraded, villagers are supposed to spawn in.

## Current Behavior

The only way to get villagers to spawn are through building or upgrading citizen huts 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Yamza** [comment]
This is a Minecolonies issue, not a pack issue.
