### ISSUE TITLE
Tooltip Error (Mekanism - maybe others too)

### ISSUE THREAD

**Issue by Leucetius** [AllTheMods/ATM3-Remix#21]
## Expected Behavior
Showing a tooltip when hovering over an item in JEI.

## Current Behavior
"Tooltip error, see log" in the tooltip

## Steps to Reproduce
1. open a table or inventory with JEI
2. search for @mekanism
3. hover over the results
4. some show the correct tooltip, some not

## Log
https://gist.github.com/Leucetius/7a9658ee0ed5e12775590a43cfc94f05#file-latest-log

the messages ar spammed all over the log

**Comment by Leucetius** [comment]
ooooh it may be my fault. I updated Nuclearcraft on my own. And the error logged with a trace says something about "nc.capability.radiation.IRadiationSource" which is something NC added in 12b

**Comment by FallenEagle1** [comment]
It is looking that way. I would guess there was something changed in the code for NC that made the other mods complain. Looks like it has to deal with the radiation and FE for energy. Out of curiousity, why did you update nuclearcraft?

**Comment by Leucetius** [comment]
To help for one :)
I like the modpack, have a github account, can read the scripts, configs and logs and want to try and help a bit.

**Comment by FallenEagle1** [comment]
Fair enough. I just wasn't sure if it was to fix a bug I was unaware of.

**Comment by Leucetius** [comment]
The changelog states a bug fixed which caused a crash in regard to reactor doors. But no, just updated to see if it throws errors (which it did :) )

Reported at NC discord and mod author stated, that the error was fixed. So I guess you can close here.

**Comment by turbodiesel4598** [comment]
Yep, my fault - will be fixed tonight :)

**Comment by Leucetius** [comment]
The 2.11c version you posted at your github resolved the error :)

**Comment by turbodiesel4598** [comment]
Awesome!
