### ISSUE TITLE
Gas Planets aren't gas planets/2 Saturns

### ISSUE THREAD

**Issue by SpottedCheetah** [AllTheMods/ATM3-Remix#215]
## Expected Behavior
Saturn, Uranus, Neptune and Jupiter should be Gas giants, but aren't. However Mercury (or rather, spelled Mercery ingame) is one, but isn't in real life.

Additionally, there are 2 planets called Saturn in the solar system

These four planets should have the flag <gasGiant>true</gasGiant> set in config/advRocketry/planetDefs.xml and it should be removed from Mercery.

**Comment by FSDel** [comment]
Also some spelling mistakes... EG. Mercury
