### ISSUE TITLE
Immersive Engineering Steel Ingot Advancement Broken

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Remix#216]
## Expected Behavior

When creating a steel ingot with immersive engineering equipment (e.g. Crude Blast Furnace) the advancement "The Upgrade" should auto complete.

## Current Behavior

When you take the steel ingots out of the crude blast furnace and put it in your inventory nothing happens.

## Possible Solution

The issue is that the steel ingot supplied is Oredict to Thermal Foundation. The solution would be to update the advancement to take accept the Thermal Foundation ingot or to Oredict all the ingots to Immersive Engineering. I understand this is a trivial issue, but for beginners or those trying to complete all the advancements this can be irritating. In my play through I was able to force the completion since I own the private server. For other players I will 

## Steps to Reproduce

1. As described above.
2.
3.
4.

## Log

N/A

## Detailed Description

As described above.

**Comment by Darkere** [comment]
Doesn't look like this is easily possible on pack level. Suggest to the devs.

**Comment by Yamza** [comment]
You can swap steel ingots with the forge lexicon as well.
