### ISSUE TITLE
Immersive Engineering Loot Tables Need Oredict

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Remix#217]
The Immersive Engineering village house has crates with nuggets and ingots as part of the loot table. The lead, nickel, and silver nuggets are incompatible in compacting drawers and other storage mediums taking up unneeded space. Suspect it is also the source of my other none standard ingots as well. Suggest updating the Immersive Engineering loot tables.

**Comment by TLomon** [comment]
Came across this in just about every mod pack I've played. You can put an ore dict converter in a storage drawer. They will then take the non-compatible items without problem.

**Comment by SpeedSlider** [comment]
smh... omg... how have I never seen that drawer upgrade. #NoobsWillAlwaysFail :P

**Comment by Darkere** [comment]
Doesn't seem like it's possible to do this without adding more mods to the pack.
