### ISSUE TITLE
Friendly reminder to review NetherEx config

### ISSUE THREAD

**Issue by OfficialStamper** [AllTheMods/ATM3-Remix#22]
If possible, I would like to see vanilla mechanics untouched, i.e. Soulsand/Netherwart. But if these are used in new recipes, then so be it.

**Comment by Lartza** [comment]
Stuff like oredicting fiery nether bricks to work as nether bricks for stuff like magma crucible would be nice at least. Haven't bumped into other issues with NetherEx yet

**Comment by FallenEagle1** [comment]
Netherrack and netherbrick added to chisel. Changed a couple things for nether wart and soul sand interaction.
