### ISSUE TITLE
Akliz Private Server Crash Report

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Remix#220]
SpeedSlider/gist:52c9384de2016cef2a46fcc1dfac9ec5

Akliz recommends 3G of ram I am currently running the server on 4. This is the second of 2 crashes while randomly exploring and loading chunks in the overworld. The crashes do happen while generating new chunks. Since I am currently running ATM3:Remix version 1.3.2 I thought I would submit the crash report here if it helps. I assume the crash is due to server ram issues as nothing stands out to me in the report.

**Comment by Yamza** [comment]
?

**Comment by SpeedSlider** [comment]
SpeedSlider/gist:52c9384de2016cef2a46fcc1dfac9ec5

Akliz recommends 3G of ram I am currently running the server on 4. This is the second of 2 crashes while randomly exploring and loading chunks in the overworld. The crashes do happen while generating new chunks. Since I am currently running ATM3:Remix version 1.3.2 I thought I would submit the crash report here if it helps. I assume the crash is due to server ram issues as nothing stands out to me in the report.

**Comment by SpeedSlider** [comment]
https://pastebin.com/vn9JxRvM


Apparently I don't know how to use GistHub.

**Comment by SpeedSlider** [comment]
Hmmm... wonder if this is what I was supposed to use in the first post.
https://gist.github.com/SpeedSlider/52c9384de2016cef2a46fcc1dfac9ec5

**Comment by Darkere** [comment]
Just a Watchdog crash. The watchdog crashes the server as lag spikes are getting too big for the current setting (it assumes the server froze). You can try adding a 0 to the max-tick-time in server.properties to make it to wait longer.
