### ISSUE TITLE
Honey Unification Needed

### ISSUE THREAD

**Issue by TLomon** [AllTheMods/ATM3-Remix#221]
## Expected Behavior

There are currently two (possibly more) liquid forms of honey in the game. Unify them as a single liquid, or at least allow them to be converted (currently only allowed with liquid XP per JEI)

## Current Behavior

Some recipes require one, some require the other. Having to mass produce both kinds is kind of silly.

## Possible Solution

I'd go with Forestry honey as the primary. Less recipes use the Rustic honey.

## Steps to Reproduce

1. Squeeze Rustic honey
2. Fill tank with Rustic liquid honey.
3. Curse when you realize it doesn't work on some Forestry machines.
4. Start a completely separate processing setup for the 2nd form of honey.

## Log

N/A

## Detailed Description

Unify both honeys as one liquid, or at least allow the liquid dictionary to use it.

**Comment by Yamza** [comment]
Liquids cannot be oredict in 1.12.2. Added a script in dev to allow conversion with the IF Fluid Dictionary Converter.
https://github.com/AllTheMods/ATM3-Remix/commit/b779db8ab4c12507c96a92691abee2bddb749460
