### ISSUE TITLE
Color for Chunk boudaries and mob spawn overlay missing

### ISSUE THREAD

**Issue by thorzy** [AllTheMods/ATM3-Remix#222]
When activating Chunkboundaries (F9) or Mob Spawn Overlay (F7) the boundary box and X'es show as grey instead of the default color making especially the mob spawn overlay nearly impossible to see.

In mod config the color values states the colors as yellow for "only spawnable at night" and red for "always spawnable" but this is not the case ingame.

The issue is consistent both in SP and on server

**Comment by Yamza** [comment]
Can you provide more information? Looks normal to me. https://i.imgur.com/K7YQgGv.png

**Comment by Darkere** [comment]
https://github.com/feldim2425/MoreOverlays/issues/62
