### ISSUE TITLE
Nuclearcraft configs need to be regenerated

### ISSUE THREAD

**Issue by Yamza** [AllTheMods/ATM3-Remix#223]
"Going from 2.15  to newest version was recommended to reset (delete and regenerate NC) configs.

Mostly it was just fuel or reactor rebalance or radiation tweaks.

Tho there were one huge fix:
Line 89, under energy_storage the Advanced Voltaic Pile have 10x more storage than it should have."

**Comment by Yamza** [comment]
@FallenEagle1 Please verify the new NC config. Wasn't fully sure which changes were intended and which were mod defaults. https://github.com/AllTheMods/ATM3-Remix/commit/76ceba07380cec293eca106c5456b6dc7fc62a2d

**Comment by FallenEagle1** [comment]
Should be fine
