### ISSUE TITLE
Some Bugs I've Noticed So Far

### ISSUE THREAD

**Issue by SirRonnieBoi** [AllTheMods/ATM3-Remix#226]
I've been playing for a little while and I've noticed a few bugs:
   The steam dynamo (thermal expansion) only outputs power when it is running (consuming resources and producing power.) Not even cables will pull out of it unless it is running. I do not know if this occurs with other dynamos, but it's probably worth a test.
   Basic mechanical pipes pull liquids out of all slots of the fractionating still regardless of whether there is an output on that side or not. For example, if the pipe is on the right side (that is set as red), it will still pull oil out of the input tank (blue slot), effectively requiring you to take apart and rebuild the entire system.
   Blazing juggernauts become lightning fast/teleport when within melee range. I'm not sure if this is intentional, but if it is, it sucks (in my opinion). This makes them extremely hard to hit, yet they seem to have no problem kicking my teeth in while I'm trying to figure out where they are, all whist they are blinking around me every 2 seconds.
   What mod makes large sections of the caves generate one block in height? It really ruins the usual mining experience. Granted, I know the idea is to get some sort of miner up and running a.s.a.p., but I still like to explore every now and then. I also don't know if this is intentional or not, but I don't really like digging away one layer of a section of cave just to get to another section.
   I don't really have much playtime in ATM3 remix yet, just switched over from ATM3, so I'll post again if I find more issues.

**Comment by Darkere** [comment]
Dynamos are intended to work like that by the mod dev.

This is not the only case where mekanism pipes are very broken. Nothing we can do about it.

Juggernauts are gone next update. 

Cave generation is heavily modified by Worley's caves. Caves very different from the normal Vanilla caves.
We've tried to reduce the amount of 1 high caves before but based on our experience and the number of complaints about it you are probably just getting unlucky with them.

**Comment by SirRonnieBoi** [comment]
Honestly the juggernaut were my biggest problem, so I'll be 1000% happier with them gone. I can work around the other stuff. I appreciate the quick response. Keep up the good work, I love the modpacks you guys make.
