### ISSUE TITLE
Bibliocraft labels glitch!!!

### ISSUE THREAD

**Issue by Richytck** [AllTheMods/ATM3-Remix#228]
## Expected Behavior
 Should stay on the storage crate after placing

## Current Behavior
After placing a label on storage crates after few moments it jumps off the crates one block away (hanging in air) 

## Possible Solution
 Make it stay still

## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description

![2019-07-22_21 57 42](https://user-images.githubusercontent.com/53196153/61665081-08a75280-accc-11e9-897a-b7cdd8f96537.png)

**Comment by Yamza** [comment]
If you have more information on this please reopen. I was not able to reproduce this issue.
