### ISSUE TITLE
Diamond Purple Shulker Box tooltip rendering crashes client

### ISSUE THREAD

**Issue by TheInfamousAlk** [AllTheMods/ATM3-Remix#229]
## Expected Behavior

Craft an upgraded shulker box of any kind, specifically I crafted a diamond purple shulker box, hover over the new item in your inventory and see the tooltip.

## Current Behavior

When hovering over a diamond purple shulker box (I believe it's from quark), the game becomes unresponsive and eventually crashes.

## Possible Solution

edit the .class file at vazkii/quark/client/feature/ShulkerBoxTooltip in the quark mod. I do not know java so I cannot give any more suggestions, but I believe that this is where the crash originates.

## Steps to Reproduce

1. Craft a purple shulker box
2. Craft upgrades for it and apply until you get a Diamond Purple Shulker Box
3. Place in inventory, then hover over item to bring up tooltip
4. Tooltip doesn't come up, and the game hangs

## Log

Crash report here:
https://gist.github.com/TheInfamousAlk/b412d215201ec9ee051c314f2b8bd955

**Comment by Yamza** [comment]
Seems to be working correctly in Remix 1.4 dev instance.
