### ISSUE TITLE
 Twitch launcher error "Object reference not set to an instance of an object" when installing the modpack.

### ISSUE THREAD

**Issue by ExperimentCode3** [AllTheMods/ATM3-Remix#231]
When installing the modpack from the twitch launcher, the installation stops and gives the error  "Object reference not set to an instance of an object." The only thing I could find after a quick google search was to contact twitch and report the error and contact the creator of the pack and report the issue. I hope to be able to play your pack soon!

**Comment by Yamza** [comment]
The issue is twitch, not the pack. You can use MultiMC instead, or wait for twitch to work.
https://www.reddit.com/r/allthemods/comments/970n2e/how_to_install_twitchmultimc/
