### ISSUE TITLE
Botania Livingwood TiC tool parts missing since pack version v1.3.2

### ISSUE THREAD

**Issue by Glendening** [AllTheMods/ATM3-Remix#236]
As of ATM3r v1.3.2 livingwood TiC tool parts vanished from the game in a newly installed copy of the mod pack. The armor parts show up for livingwood but no tool parts.

## Expected Behavior
Livingwood should be craftable into TiC tool parts via PlusTiC mod and last were in ATM3r v1.3.1

## Current Behavior
Livingwood can only be crafted into TiC armor parts, not tool parts in pack version 1.3.2, 1.4.0, and 1.4.9

## Possible Solution
Unsure?

## Steps to Reproduce
1. Install ATM3r 1.3.2, 1.4.0, or 1.4.9 via Twitch
2. Load into a SP world
3. Livingwood TiC parts can not be crafted and are not listed in the items list

## Log
N/A

## Detailed Description
Further testing:
Loading a custom modpack with latest version of  TiC, Botania, PlusTIC, Armoy expansion, Tinkers Armory allows the livingwood to be crafted into TiC tool parts
ATM3r v1.3.2 to 1.4.9 all are using the same (latest) version of these mods.
It appears this may be a configuration issue or a conflict with some other mod I have not tested yet.

**Comment by Yamza** [comment]
Confirmed that this is not working. https://i.imgur.com/WNeb9Oy.png

**Comment by Yamza** [comment]
May be related to these:
https://github.com/Landmaster/PlusTiC/issues/295
https://github.com/YaibaToKen/Armory-Expansion/issues/36#issuecomment-490577897

**Comment by Glendening** [comment]
Running the newest version of those mods (which remix 1.3.2-1.4.9 is doing) that issue was resolved and the living wood parts show up fine outside the remix pack.

**Comment by Glendening** [comment]
Issue is resolved by deleting the armory expansion configs then loading the mod pack per note on 1.3.1 update for armory expansion
"Warning: When updating to v1.3.1, please delete your config files. Breaking changes were introduced with the latest revision in order to fix a major bug."

**Comment by Glendening** [comment]
Update. Not resolved.
Issue only resolved once after deleting configs. Reloading the game a second time shows the issue has returned. The configs need deleted each time you load the game.

**Comment by Glendening** [comment]
#https://github.com/YaibaToKen/Armory-Expansion/issues/55

**Comment by Glendening** [comment]
Per testing it looks like setting 
B:conarm=false
In all the mods 3 remix>config>armoryexpansion.cfg
Resolves the issue for now but also drops a lot of armor parts made of various materials

**Comment by Yamza** [comment]
Fixed with mod update.
