### ISSUE TITLE
End Biotite Doesn't Generate and is Unobtainable 

### ISSUE THREAD

**Issue by GioHiTech** [AllTheMods/ATM3-Remix#238]
## Expected Behavior
Biotite ore should spawn in the End after the Ender Dragon is killed

## Current Behavior
Biotite ore doesn't spawn at all, and therefore makes the building blocks unobtainable

## Possible Solution
Maybe checking configs can help

**Comment by Yamza** [comment]
Biotite is configured to not spawn. The recipes using it should have been changed to need something else.
