### ISSUE TITLE
World edit rotate not changing stair block orientation

### ISSUE THREAD

**Issue by despian** [AllTheMods/ATM3-Remix#239]
## Expected Behavior

When rotating a selection in world edit the orientation of any stair blocks within that area should also be rotated.

## Current Behavior

The orientation of the stair blocks are not changing.

## Steps to Reproduce

1. Build stairs (i'm using "astralsorcery:blockmarblestairs")
2. Select area with world edit
3. //copy
4. //rotate 90
5. //paste

## Modpack version

1.4.0

**Comment by Yamza** [comment]
You should check if this is simple an issue with worldedit, which I suspect it is. 
If you confirm that it is not an issue with worldedit please reply again. 
If it is an issue with worldedit you should report it to them.

**Comment by despian** [comment]
This does not normally happen with world edit. Maybe the version of world edit in the pack needs to be updated or maybe it's an issue with the type of block. I'll try with vanilla stairs.

**Comment by despian** [comment]
So this issue is kind of a problem with worldedit 6 but can be fixed here if you want.

we6 uses a pre complied block registry to determine how different types of blocks should be rotated. The default packaged with the mod only contains the vanilla blocks.

They have a dev tool on their github which will generate the blocks file which can then replace the one packaged with the mod.

https://github.com/EngineHub/ForgeUtils

You could generate this file for the modpack and included it in this repo with a script which replaces it. Or just package a version of the worldedit.jar containing the file.

I have generated the correct blocks.jar for version 1.4 and it's working fine on my server. I can share it if you want it.

This isn't an issue with we7 but I think that version isn't compatible with mc1.12.

**Comment by tyon2006** [comment]
How do you use ForgeUtils to dump the blocks? Their site has no documentation and they didn't want to offer support in their discord. I built a copy from the repo and ran the game with it, but nothing happens and it doesn't appear to add a command.
