### ISSUE TITLE
wizardry stuck in loading, jump from underworld

### ISSUE THREAD

**Issue by jiliangw** [AllTheMods/ATM3-Remix#240]
doing wizardry mod
https://github.com/TeamWizardry/Wizardry

i jumped from overworld from a very high place and crashed into the underworld
everything worked fine.
killed some fairies and unicorn
the book says i have to jump from the underworld to get to normal world.
did that
stuck in infinite loading.
the world and play time is lost now!

## Expected Behavior
jump from the underworld.
back somewhere in the overworld. not DEAD
don't now where the perfect location should be.
because this mod never worked....

## Current Behavior
i jumped from the underworld to get back in overworld
world is not playable. it stays in loading

## Possible Solution
not sure if i died and the gravestone mod cant handle it? or something else
but it is certainly Wizardry mods fault.

## Steps to Reproduce
1.jump from a very high play onto bedrock to get into underworld
2.once in underwold. jump somewhere into the void
3. issues reproduced.

## Log
there is no crash, just stuck in infinite loading

## Detailed Description
didnt know if i should post it here or the wizardry mod

**Comment by FallenEagle1** [comment]
Have you tried relogging? Also, what version of the modpack (please do not just say latest)

**Comment by jiliangw** [comment]
yeah， if i say it's latest.  there is a date on the comment. 

it's 1.4.9. all the mods remix. 

I fixed by: using NBTexplorer and changed dimension and location to spawn point. 
then used the command /tbrestoreInventory to restore everything I had on me.

**Comment by FallenEagle1** [comment]
Doesnt matter what the date on the comment is, what the latest version of the pack is does not always correspond with what people think they see is the latest, and it just adds confusion because many times two different versions of the pack are being talked about, but assumed is the same.

Still going to look into this, and double check the dimension teleporting works as intended.
