### ISSUE TITLE
Error Loading ATM3: Remix

### ISSUE THREAD

**Issue by HeftyEagle** [AllTheMods/ATM3-Remix#246]
## Expected Behavior

The pack should load

## Current Behavior

Doesn't load

## Possible Solution

Ender IO fatal recipe error 
Says to report this to the modpack creator and not to Ender IO Team

## Steps to Reproduce

1.
2.
3.
4.

## Log

https://gist.github.com/HeftyEagle/13174ab9d41b7c1f196d92a05566a116

## Detailed Description

I do not know whats going on but i have redownloaded the pack a couple times and this continues to happen i am on version 1.4.9 as well as the server version never loading as well

**Comment by HeftyEagle** [comment]
Sorry about this my friend was having me disable oeintergration as he dislikes not being able to use OreExcavtion in the beginning of the world everything seems to be working now

**Comment by FallenEagle1** [comment]
You can go into the oeintegration config file and disable that part if you really want. Its a better way than disabling the mod.

**Comment by HeftyEagle** [comment]
Thank you for getting back to me so soon

**Comment by Darkere** [comment]
You are also having some issues with other programs blocking access to the install. It would be a good idea to move it somewhere else.
