### ISSUE TITLE
How to breed Agricraft seeds?

### ISSUE THREAD

**Issue by obuw** [AllTheMods/ATM3-Remix#247]
The ways I usually use to breed agricraft seeds (to get them to 10/10/10) all seem to be disabled. Is there any way to upgrade seeds (without adjusting the configs), or is it intentionally disabled?

**Comment by Yamza** [comment]
It should work for any non-resource seed, mystical agriculture and such are intentionally disabled.

**Comment by obuw** [comment]
How? I tried breeding sugarcane and pumpkins, neither went above 1/1/1.

**Comment by ewanm89** [comment]
you using cross crops?
![image](https://user-images.githubusercontent.com/135458/62792887-2516fd80-bac8-11e9-86f1-bfa53676e7dc.png)

Need the one on the right to increase the value, not the left.

**Comment by obuw** [comment]
Yep. I have 4 regular crops with a cross crop in the middle.

  c
cxc
  c

But you know, you are making me second guess myself now. :P I will boot the game up and try again to see if I was doing something wrong.

**Comment by Yamza** [comment]
Have you been able to resolve this @obuw?

**Comment by obuw** [comment]
Indeed I was able to resolve it. I had to make sure all the parents were identified, and then use cross cropsticks, and it finally started working.

Thanks for the help!
