### ISSUE TITLE
Amber dupe

### ISSUE THREAD

**Issue by Arakoth** [AllTheMods/ATM3-Remix#248]
## Expected Behavior

4 pieces of amber can be crafted as a 2x2 to create a block of amber.
That block should be convertable back into 4 pieces of amber  - ie what you started with.
(To be consistent with ingots and blocks, albeit with a 2x2 recipe rather thana  3x3)

This is in ATM3 Remix 1.4.9, unsure if it was present in earlier versions.

## Current Behavior

You get more amber out of a block than is needed to craft the block in the first place, all through the magic of a crafting table.

## Steps to Reproduce

1. 4 pieces of thaumcraft amber in a 2x2 craft into 1 block of thaumcraft amber.
2. 1 block of thaumcraft amber crafts into 9 pieces of biomes o'plenty amber.
3. 2 pieces of biomes o'plenty amber in a 1x2 crafts into 2 pieces of thaumcraft amber.
So 4 pieces of thaumcraft amber turn into 1 block which turns into 9 biomes amber, into 8 thaumcraft amber and a spare biomes piece.

Note that an alternative to step 3 is to just put the biomes o'plenty amber in a 2x2 grid to make new thaumcraft amber blocks.

**Comment by joan-rivers** [comment]
so many dupes in this pack ! wow !
