### ISSUE TITLE
Recipe Conflict Brewing Stand: Potion of Love & Potion of Relapse.

### ISSUE THREAD

**Issue by KaneHart** [AllTheMods/ATM3-Remix#25]
Not Sure if this is a Joke:
I'm not sure if this was sure if this was suppose to be satire on the developers point of view or not as it's his own 2 recipes conflicting. 

Issue:
Potion of Love fully works but every time you craft it you end up with Potion of Relapse instead. 

Reported to the dev years ago:
https://github.com/rwtema/extrautilities_old_issues/issues/969

ATM3 suffers from the same recipe issue.

**Comment by Yoosk** [comment]
fixed with https://github.com/AllTheMods/ATM3-Remix/commit/68b797af20550063edfdf44922676d0be076e1da
