### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by Goretantath** [AllTheMods/ATM3-Remix#253]
I was wondering if these could be added without too much issue, if not its totally understandable.

Electroblob's Wizardry "Fan Spell Packs"
https://www.curseforge.com/minecraft/mc-mods/arcane-essentials(adds more spells)

https://www.curseforge.com/minecraft/mc-mods/extra-spells-electroblobs-wizardry(adds new spells, even more with potion core)

https://www.curseforge.com/minecraft/mc-mods/potion-core(adds new potions)
___________________________________________________________________________________________________
Psi Addons
https://www.curseforge.com/minecraft/mc-mods/random-psideas(adds more tricks)(reason should be added:The Psi Compendium has so many awesome spells that i cant use because they require this mod)
https://www.curseforge.com/minecraft/mc-mods/psionic-upgrades(adds more tricks, functions and items)
https://www.curseforge.com/minecraft/mc-mods/psionic-peripherals(adds a bow that accepts spells)(the bow spells we currently can make dont ammount to much since its usualy just stopping the arrow in a block then accelerating it into the mob)
___________________________________________________________________________________________________
QoL Mods (To me at-least)
https://www.curseforge.com/minecraft/mc-mods/future-mc(adds in components from newer official minecraft versions)(Reason to add:Even MORE reason not to update from 1.12.2 :D)
https://www.curseforge.com/minecraft/mc-mods/charm(adds new decorations plus some new textures to wolves and cats)(Reason to add: varied cats and dogs? heck yeah!)
(Most likely too intesive but figured i'd include just in-case a miracle would occur xd)https://www.curseforge.com/minecraft/mc-mods/better-animations-collection-2(Just makes mobs look AWESOME)(reason to add:realisim? idk i just loved that things have KNEES now)

**Comment by FallenEagle1** [comment]
We have a mod suggestion issue open already, I would suggest closing this issue and putting these onto that suggestion issue

**Comment by FallenEagle1** [comment]
Going to close this. These are decent suggestions, but for them to be considered, I would suggest putting them on the correct issue (#10 )
