### ISSUE TITLE
Mekanism Thermal Evaporation Plant Visual Bug

### ISSUE THREAD

**Issue by thepovinater** [AllTheMods/ATM3-Remix#254]
After creating the mekanism multiblock thermal evaporation plant, which is required for ore quadrupling in the pack, a visual bug occurs. This happens after the thermal evaporation controller is placed in the multiblock structure.  You are able to enter the UI of the controller if it is not a part of the multiblock, however once water is pumped into the valve and the temperature rises to create brine, a visual bug occurs. This bug causes the screen to gray out with the game being functional in the background. The only way to fix the bug is to break the multiblock structure. 

## Expected Behavior
The multiblock structure forms as normal and the player should be able to pipe in water, which will turn into brine that can be piped out through the valve to be used to create HCl, a component used for ore quadrupling.

## Current Behavior
At the moment that the multiblock is created, a visual bug occurs where the player's screen is completely grayed out while playing, even in the menu screen. This issue has occurred for me in at least 2 dimensions, the overworld as well as within a large compact machine.

## Possible Solution
In the short term, breaking the multiblock structure makes the game playable, but long term, I am not sure what will fix this issue.

## Steps to Reproduce

1. Create the thermal evaporation plant outline of the multiblock using the thermal evaporation blocks and add the 2 valves to the structure.
2. Insert the thermal evaporation controller into the structure and pump water into the structure.

## Log
N/A because the game doesn't crash with this visual bug.

**Comment by FallenEagle1** [comment]
Do you have optifine? As it seems to have issues with mek multiblock structures.

**Comment by thepovinater** [comment]
I just checked my mod list for the pack now and I do not have optifine installed

**Comment by Yamza** [comment]
https://github.com/mekanism/Mekanism/issues/5579
Temp solution is here.
"in BetterFPS changing Fog from Fast to Fancy seems to make it work properly."

**Comment by thepovinater** [comment]
That worked as a temporary solution. Thanks Yamza!
