### ISSUE TITLE
Quark Item linking not functioning 

### ISSUE THREAD

**Issue by Tops420** [AllTheMods/ATM3-Remix#257]
Shift+T does not produce an item link in the chat window, server multiplayer/ single player after 1.4.9 update

## Expected Behavior

A link should appear in the chat window of the item you shift+T'd in your inventory

## Current Behavior

Nothing

## Possible Solution

Dunno

## Steps to Reproduce

1. Open Inventory
2. Mouse over an item and hit Shift+T
3.
4.

## Detailed Description

Track down and squash the bug :P

**Comment by Yamza** [comment]
Working in dev instance. Double check this before release.

**Comment by canalpa** [comment]
I am having the exact same issue and so is 15+ people in my server

**Comment by canalpa** [comment]
![quark](https://user-images.githubusercontent.com/5249246/63232708-8e012280-c1f8-11e9-9a3a-3dddb2031bad.png)

**Comment by Sleeeper** [comment]
It works for ops but not for regular players.

**Comment by Yamza** [comment]
Seems fine in dev. OP and not OP.
