### ISSUE TITLE
Draconic Evolution Tablet not downloading?/functioning

### ISSUE THREAD

**Issue by Tops420** [AllTheMods/ATM3-Remix#258]
Draconic Evolution Information Tablet not opening correctly, or downloading from its source to display its contents

## Expected Behavior

It should open correctly

## Current Behavior

it gives this error. and i ran into another displayed error lastnight, but didnt catch it with a screenshot. had a link to a brandon webpage

https://cdn.discordapp.com/attachments/163076434229854209/612699726168457251/unknown.png

## Possible Solution

Perhaps a server issue from the mods side?

## Steps to Reproduce

1. Open the tablet in any form, standalone or from the tome
2.
3.
4.

**Comment by Yamza** [comment]
This can potentially be fixed by adding vanillafix, but vanillafix crashes with foamfix. Not Really a good solution.
Also isn't reproducible for everyone.
https://github.com/brandon3055/ProjectIntelligence/issues/1

**Comment by ewanm89** [comment]
Mine was doing this, and then it suddenly started working.
