### ISSUE TITLE
[0.0.3] Food Saturation is displayed incorrectly. 

### ISSUE THREAD

**Issue by KaneHart** [AllTheMods/ATM3-Remix#26]
## Expected Behavior
If you hover over steak it should give you 6 1/2 of saturation. When you eat it should give you the number displayed.

## Current Behavior
Gives you 3 foods 1/4 saturation but I'm not 100% on that sometimes other foods it seems even less then that but I think it's because I'm dealing in fractions.

**Comment by FallenEagle1** [comment]
Just notes as I jump in and out of trying to find the issue on this.
Doesnt cause this:
Birds foods
Nutrition

**Comment by Lartza** [comment]
It's Random Tweaks.
Setting B:carryExcessHungerToSaturation=false to true in it's settings kind of fixes this, but I can't see a way to restore total vanilla mechanics.

**Comment by Lartza** [comment]
Issue is to be fixed with Random Tweaks 2.1.3.2 when it releases. Seems we also get a config option to disable RT from touching hunger mechanics as a plus.
