### ISSUE TITLE
Can no longer access my world.

### ISSUE THREAD

**Issue by derpybird39** [AllTheMods/ATM3-Remix#262]
When i try to load into my world I get through the loading screen, however when i load in im in a void. This causes the game to freeze and the game eventually crashes. I am getting an exception in server tick loop error.

Error: java.lang.NullPointerException: Exception in server tick loop

Pastebin: https://pastebin.com/95ge2VZ6

**Comment by Yamza** [comment]
Did something happen prior to this, like the game wasn't properly closed during the last session?

**Comment by derpybird39** [comment]
I was in the twilight forest and my game crashed. My game used to crash frequently as i dont have the best computer, but this error has never occured until now.

**Comment by Vintschente** [comment]
Exception in server tick loop means the server (in this case your computer if you play only locally) skips over 60 ticks per minute thus shutting down itself cause it can't handle the load anymore. So there is something that made your world lag horribly. Try editing your user location in the file so you are in the overworld instead and delete the folder with the twilight forest ID. Then start your world again.

**Comment by Darkere** [comment]
No. In that case, the Error Message would be along the lines of:
"Watchdog detected that the current tick took longer than 60s. should be 0.05s"

Exception in server tick loop just means the error appeared while the server was processing the ticking. In this case, a player was moving and loading chunks at which point the error appeared.
