### ISSUE TITLE
agricraft sprinklers laggy

### ISSUE THREAD

**Issue by flamingram** [AllTheMods/ATM3-Remix#266]
## Expected Behavior

by default the agricraft sprinklers should be turned off ahnd motion less so the lagg wont be crazy

## Current Behavior

particles are completly on  causing huge amount of personel and server lag

## Possible Solution

make the agricraft sprinklers particle effects off

## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description

so i did try to disable particles in the config but it dosent work

**Comment by Ki-Tan2934** [comment]
Turn off particles and use lag goggles to find fps lag
