### ISSUE TITLE
craftTweaker crash on startup - unregistered item cyclicmagic:clock

### ISSUE THREAD

**Issue by ZizzyZizzy** [AllTheMods/ATM3-Remix#267]
Version 1.4.9 client from the Twitch launcher crashes when trying to connect to a server.

`com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Recipe crafttweaker:cmclock (crafttweaker.mc1120.recipes.MCRecipeShaped@1c86a9d6) produces unregistered item cyclicmagic:clock (net.minecraft.item.ItemBlock@39e55d)`

Had the same problem on ATM3 v5.12.3. I tried disabling cyclicmagic in the crafttweaker config file on the client and the server - Same error.

Version 1.3.0 works perfectly.

**Comment by Yoosk** [comment]
Without the crash-report from your side and latest.log from server side, we wont be able to tell much.
