### ISSUE TITLE
"Energy Core" recipe doesn't work

### ISSUE THREAD

**Issue by Vintschente** [AllTheMods/ATM3-Remix#268]
"Energy Core" for crafting the "Unified Field Core" and thus the ATM star doesn't work. I am trying this in a vanilla workbench. All items are charged and at 100% at everything shown.

modpack version: 1.4.9
![energy core](https://user-images.githubusercontent.com/17528773/64124942-aea8ab00-cda8-11e9-908a-0febe62133ce.png)

**Comment by Yamza** [comment]
The crystals need to be actually 100 in all stats, you should be able to see this by enabling advanced tooltips (f3 + g) then holding ctrl over them.

**Comment by Vintschente** [comment]
As I mentioned all stats are at 100% and I can see this even without the advanced tooltips. Maybe it is worth mentioning that despite all crystals are at 100% in everything, I have 3 "different" types that I can't stack on each other. Any other hints?

Thank you in advance

**Comment by Yamza** [comment]
The stats are more likely at 99.5%+ which rounds up to 100, which is why I suggested advanced tooltips.

**Comment by Vintschente** [comment]
I had to press ctrl and shift at the same tip and then it is shown somewhere below. Thanks!
But why would it round up? Makes no sense to round it up when exactly 100% are required which you normally don't see.

**Comment by Yamza** [comment]
Crafttweaker can only read exact values and the mod allows the values to be more than round numbers.
