### ISSUE TITLE
Chaotic tools not shown for PlusTIC

### ISSUE THREAD

**Issue by KiritoKun223** [AllTheMods/ATM3-Remix#270]
## Expected Behavior
Usually you should be able to build draconic long-swords with chaotic cores for example. 

## Current Behavior
It's just not possible and they are also not shown in JEI.

## Possible Solution
It might just be a config change? A different modpack has similar mods and it has this option.

## Steps to Reproduce
1. Search for Chaotic in JEI
2. You will only find the armor.

## Detailed Description
Try to make it available again

**Comment by Yamza** [comment]
https://github.com/AllTheMods/ATM3-Remix/issues/236
