### ISSUE TITLE
Strange graphic glitch when using dynamic tanks for distillation tower 

### ISSUE THREAD

**Issue by AmericanGOPHER** [AllTheMods/ATM3-Remix#271]
## Expected Behavior

The fluid should just fill in the tank.

## Current Behavior

Every time i enter this particular chunk the whole screen turns blank. The game still runs in the background however and the graphics return to normal when the problem chunk is left. 

## Possible Solution

I tried turning my fog to fast because it solved a similar problem I had with the thermal station. The mekanism one. You know. It makes brine. However, that didn't seem to solve the issue. In fact, the problem isn't even exactly the same. With the thermal station the problem only occured when you looked at the station. However, the issue now seems to be when i enter this particular affected area. 

## Steps to Reproduce

1. Build an immersive engineering fluid jack
2. connect it to the immersive engineering distillation tower
3. use mekanism mechanical pipes to pump crude oil into distillation tower
4. use mekanism mechanical pipes to pump various byproducts into mekansim dynamic tanks.  

## Detailed Description

The glitch seems to only be affecting where one of the tanks was. I've removed the tanks, the pipes, the tower, and even the fluid jack. Unfortunately, the graphical glitch is still there. I am using sphax bdcraft resource pack and I will try to remove that to see if it works. 

Yeah, changing resource pack did not fix the issue

**Comment by Ki-Tan2934** [comment]
Make a new issue if this is still a problem
