### ISSUE TITLE
Dark boots from ender io not negating fall damage when powered

### ISSUE THREAD

**Issue by thatguy34u** [AllTheMods/ATM3-Remix#277]
## Expected Behavior
Should negate all fall damage when powered

## Current Behavior
Only negates fall damage about 70% of the time. Fall damage is taken most of the time when just jumping once without moving or when jumping on same block level.  

## Steps to Reproduce

1.jump with powered dark boots 
2.hit floor and take damage
3.
4.

**Comment by Glendening** [comment]
OH! So today I can replicate it. =|
Yep this is happening. If you cheat in fully upgraded dark boots then do a short jump straight up you take damage each time you hit the ground. That should not be happening.

**Comment by Glendening** [comment]
Verified this is not an issue with a modpack consisting of just Ender IO and nothing else. Looks like it might be some sort of interaction between mods.

**Comment by Glendening** [comment]
Upgraded enderboots are also showing the same issue.

**Comment by Yamza** [comment]
Unsure what could be causing this. If anyone has info please let us know.
