### ISSUE TITLE
Netherex Crashes After Latest Update

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Remix#278]
After updating and playing a little on my private server I was unable to log in as the server was stuck in a crash loop. I did nothing in the nether other than deleted the old dim file and ensure a new nether was generated.

https://gist.github.com/SpeedSlider/c64d99746294299d426d9d7d796a9bea

## Expected Behavior
Server should run continuously as it has before the latest update.

## Current Behavior
Server stuck in a crash loop.

## Possible Solution
I will be deleting the nether dim and restarting the server. The only thing I can think is that I am not currently playing on the server much and I had a nether portal within 100 blocks of spawn.

## Steps to Reproduce
N/A

## Log
https://gist.github.com/SpeedSlider/c64d99746294299d426d9d7d796a9bea

## Detailed Description
Mostly I am posting this for the crash report. I have done no troubleshooting at this point. Prior to updating to 1.5.0. the server ran fine and I had limited issues. After updating which including deleting the nether files the server got stuck in a crash loop. I manually stopped the server and restarted it and it crashed. At this point I can only assume that I left the nether portal active within 500 blocks of spawn which had the nether constantly loaded. Previously, I had deactivated the portal and used waystones to get to the nether.

**Comment by Yamza** [comment]
Fixed in 1.5.1.
