### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by DrTHC** [AllTheMods/ATM3-Remix#280]
## Expected Behavior
I expect it to crash sometimes due to it being heavily modded game.

## Current Behavior
crashes all the time and on different computers.

## Steps to Reproduce

1. Search cable in JEI
2. Search Facade in JEI
3. Search Power in JEI
4. If server gets lag it throws game off and cause that to stall and sometimes crash
5. There are more but I can't rememeber.

## Detailed Description
If there is a possible fix for this

I'm currently running 16gb RAM (10GB allocated to game)  I5 6500K 1060 6GB.

Thanks

**Comment by FallenEagle1** [comment]
A crash report would be beneficial, otherwise it's just a guessing game as to what the actual issue is. They can be found in the crash reports folder of the main minecraft folder. Put them on pastebin or gist.github
