### ISSUE TITLE
Thaumcraft Amber Block not craftable and cant OreDictionary it

### ISSUE THREAD

**Issue by Vavyo** [AllTheMods/ATM3-Remix#283]
## Expected Behavior
Crafting Thaumcraft amber in a 3x3 should produce a Thaumcraft amber block or the BoP amber block should have a conversion recipe into the Thaumcraft version. The BoP amber block should also be able to be used in the crafting of the Arcane Lamp due to OreDict

## Current Behavior
There is no way to OreDict or craft the Thaumcraft amber block. The only available amber block is from BoP and it doesn't work for the arcane lamp recipe even though they both have the OreDict tag - blockAmber. Due to this the arcane lamp and recipes requiring it cannot be crafted.

## Possible Solutions
Add: shapeless 2 BoP Amber <-> shapeless 2 Thaumcraft Amber recipes so they can be interchanged. 
Allow Bop Amber to be used in the crafting of the arcane lamp.
Allow Bop Amber to be used in the crafting of amber bricks from Thaumcraft.

## Steps to Reproduce

1. Attempt to craft Thaumcraft amber
2. Attempt to craft the arcane lamp
3. Attempt to craft amber bricks

## Detailed Description
This is a fix that would allow players to use Thaumcraft 6 amber blocks as a building material as well as allow the crafting of the arcane lamp using Biomes O' Plenty amber blocks.

**Comment by FallenEagle1** [comment]
What version of the modpack?

**Comment by Vavyo** [comment]
Modpack version: 1.5.0

**Comment by incomingnerd** [comment]
It's also broken in 1.5.1

**Comment by Darkere** [comment]
You can convert between BoP Amber block and Thaumcraft amber block with the forge lexicon.

**Comment by incomingnerd** [comment]
I thought I tried that and it did nothing.

**Comment by incomingnerd** [comment]
In my install I've just changed atm_oredict_ores.zs so amberblockconvert produces the Thaumcraft blocks instead. It's a bit of a kludge, but at least I can craft the lamp now.

I'd also vote for switching the pack to using the Thaumcraft amber in preference. BOP gem blocks are basically only used for bulk storage whereas the Thaumcraft amber has actual uses. Plus, IMHO, Thaumcraft has much better textures.

**Comment by Darkere** [comment]
I'm unsure why both mekanism and industrial foregoing don't want to transform that. But the forge lexicon and the Lexical transmuter both work.

**Comment by incomingnerd** [comment]
Ah, yeah I forgot exactly how the Lexical Transmuter worked in conjunction with the Lexicon. I'm keeping my altered configs though - bulk conversion is easier with a crafting recipe.
