### ISSUE TITLE
Tinkers' Construct Mending Moss Doesn't Work Possibly Due to XP Clumping Mod

### ISSUE THREAD

**Issue by Samork** [AllTheMods/ATM3-Remix#284]
## Expected Behavior
After applying mending moss to tools, every XP you collect off the floor should be stored in these tools and this XP should slowly repair tools over time.

## Current Behavior
None of the many ways of gaining XP gets stored in mending moss applied tools. Therefore not repairing it.

## Possible Solution
There should be a mod that clumps XP together to fix any possible lag that XP orbs might cause; this mod should be updated.

## Steps to Reproduce
1. Add mending moss to any Tinkers' Construct tool
2. Use it's durability (hit something, break something)
3. Collect XP off the floor
4. Check the tool to see that it didn't store any XP and it isn't getting repaired.

## Detailed Description
Clumps Mod (XP Orbs clump together) should be updated to work with Tinkers' Construct's XP storing, auto repairing tool modifier.

**Comment by Ki-Tan2934** [comment]
Make a new issue if this is still a problem
