### ISSUE TITLE
Immersive Petroleum not in liquid dictionary

### ISSUE THREAD

**Issue by CrystalMare** [AllTheMods/ATM3-Remix#285]
Diesel from immersive engineering can be turned into kerosine and then into gasoline, which can then be processed into LPG. However, the Gasoline produced by the same distilling tower as the diesel, does not allow processing into LPG.

Below, a process flow diagram, the oil, diesel and gasoline on the left are Immersive engineering. Kerosine is created by pneumaticraft.
```
Oil -> Diesel -> Kerosine -> Gasoline -> LPG
    -> Gasoline  -----------^ 
```

## Expected Behavior
Immersive engineer's gasoline shares liquid dictionary with the gasoline from pneumaticraft

## Current Behavior
Machine does not accept immersive engineering gasoline.
Machine does accept immersive engineering diesel.

## Possible Solution
Adding entry to liquid dictionary

**Comment by Ki-Tan2934** [comment]
Make a new issue if this is still a problem
