### ISSUE TITLE
1.5.1 crashes

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Remix#286]
https://gist.github.com/SpeedSlider/6c69c89e49c0d1967c0e9f7f6c4639d0

## Expected Behavior
Game should load after updating.

## Current Behavior
Game crashes during loading. It normally will crash on first attempt, but continued through 2nd and 3r.

## Possible Solution
NetherEx crashes :/

## Steps to Reproduce

1. update from 1.4.9
2. Try to load :P
3.
4.

## Log
https://gist.github.com/SpeedSlider/6c69c89e49c0d1967c0e9f7f6c4639d0

## Detailed Description
see above

**Comment by FallenEagle1** [comment]
Delete the netherex config file and let it regen
