### ISSUE TITLE
Mica from environmental tech does not get produced by void miners.

### ISSUE THREAD

**Issue by luckcolors** [AllTheMods/ATM3-Remix#287]
## Expected Behavior
The mica block is used for crafting all the modifiers for environmental tech's multiblock mahcines.
For some reason it doesn't seem to get produced by the void mining lasers and no alternative recipe exists.
This makes it impossible to upgrade the void miners and to use the effect modifiers in the nanobot beacon.

## Current Behavior
The mica is not produced by the void miner

## Possible Solution
Possibly not applicable because being in an older pack: https://forum.feed-the-beast.com/threads/mica-not-created-from-void-ore-miner.184951/

## Steps to Reproduce
1. Create a void miner.
2. Let it run for a long while.

## Log
No log neccessary.

## Detailed Description
Enabling the mica would allow to increase the speed for the void miners and that could make the laser itself too good for creating resources. (recipe could be tweaked for end game?)
But it is a necessity for using the nanobot beacon.

**Comment by Darkere** [comment]
Read again where mica comes from. Mica comes from the Void RESOURCE miner not the Void ORE miner.

**Comment by luckcolors** [comment]
Ah, sorry about the issue then and thanks for the help! 💯
