### ISSUE TITLE
Game freeze sometimes when water sound? is played or water starts flowing?

### ISSUE THREAD

**Issue by SEUH** [AllTheMods/ATM3-Remix#288]
I am not exactly sure what is causing the freeze but it always freezes when another person on the server starts a water flow (with bucket or by breaking a block which is underneath water). Also the distance is important, if i am near him like 5 blocks max. it doesn't crash and if i am in another dimension it doesn't crash as well. Also it is very hard to tell because we couldn't reproduce it, it just happens when he does something with water.

## Expected Behavior
Obiously the game shouldn't freeze

## Current Behavior
Game freezes

## Steps to Reproduce
Hm, join a server with a friend, do something and let your friend play with water near you.

## Log
No crash report and nothing in latest.log. It just freezes. Also looked with virtualvm and everything seems normal when game is frozen.

**Comment by Yamza** [comment]
Still would like to see a latest log from when the issue was happening. Otherwise don't really have anything to go on.
