### ISSUE TITLE
AE2: Ultimate Wireless Terminal moving items from inventory to AE storage using shift

### ISSUE THREAD

**Issue by PaprikaCayenne** [AllTheMods/ATM3-Remix#289]
Whenever I try to move items from my inventory to AE2 Storage using wireless Ultimate Terminal. If I use Shift Click it moves it to the trash area and then the error below pops up and either the server crashes or all the items in the terminal window disappear next time I open it.

## Expected Behavior

Item should move into AE2 Storage and the terminal should keep working

## Current Behavior

Either game crashes or terminal stops showing items. Both ways the error below shows up on the server. The drives still show items are populating though. This only started after I added Fluid Drives. I tried to remove them and it still happens

## Steps to Reproduce

1. Open up Ultimate Wireless Terminal
2. Hold Shift
3. Click on Item
4. Item moves to trash section of terminal. Error shows up on server and crashes or next time you open up the terminal all items are missing. Have to restart server.

## Log

https://gist.github.com/PaprikaCayenne/bf407dafa0291f2d91cfff757bf37131

**Comment by Ki-Tan2934** [comment]
Make a new issue if this is still a problem
