### ISSUE TITLE
Hang in SP or disconnect in MP when charging wireless crafting terminal via items from Simply Jetpacks 2

### ISSUE THREAD

**Issue by MrPipperz** [AllTheMods/ATM3-Remix#290]
## Expected Behavior
Have charged item from Simply Jetpacks 2 in inventory
Use Wireless Crafting Terminal
WCT should charge via SJ2 item

## Current Behavior
Internal server error forces a disconnect in MP or game hangs in SP

## Possible Solution
Update SJ2 version in pack to version 2.2.14.67 as it fixes this issue specifically
OR include an up-to-date version of Redstone Repository

## Steps to Reproduce
1. Have charged item from Simply Jetpacks 2 in inventory
2. Use Wireless Crafting Terminal
3. WCT should charge via SJ2 item

## Log

https://gist.github.com/MrPipperz/b79127212018947a4fdfc93f666987b8

**Comment by Darkere** [comment]
This is likely caused by WCT. It doesn't charge in other cases like wireless charging at all. 

Carry a capacitor instead.
