### ISSUE TITLE
Thorium Dust Smelting

### ISSUE THREAD

**Issue by SubjectHawk66** [AllTheMods/ATM3-Remix#291]
## Expected Behavior
Thorium should be smelt-able by all smelting machines.

## Current Behavior
Only smelt-able by Redstone Furnace, Arc Furnace, Induction Smelter, and TC Smeltery if you'd count that.

## Possible Solution
Adding recipes to all available smelting machines in some way with crafttweaker.

## Steps to Reproduce

1. Look at uses of Thorium Dust
2.
3.
4. Not what you wanted I bet.

## Detailed Description
Was just about to setup an automatic smelting system for ores with something other than Thermal Expansion and it's hard without that. If that's what was intended so be it but if so it should maybe be harder to process.

**Comment by Ki-Tan2934** [comment]
Make a new issue if this is still a problem
