### ISSUE TITLE
Yellorium Obtainable through Mek

### ISSUE THREAD

**Issue by SubjectHawk66** [AllTheMods/ATM3-Remix#292]
## Expected Behavior
Yellorium should be unattainable.

## Current Behavior
You can process uranium through Mekanism's Enrichment Chamber and Energized Smelter and get yellorium dust and then yellorium.

## Possible Solution
Idk how that happened tbh you removed the recipe for it.

## Steps to Reproduce

1. Process Uranium ore through Enrch Chmbr and Enrg Smltr
2.
3.
4.

## Detailed Description
Yellorium is just Uranium wearing a yellow, full body spandex suit.

**Comment by FallenEagle1** [comment]
Was about to say this is a duplicate, but that issue is over on the atm3 github. Boils down to an issue with ore unification (jaopca and unifier) so fixes for this may be limited. Still should be looked into.

**Comment by whatthedrunk** [comment]
seems to only output IC2 crushed in my 1.5.3 test that will be out later today. Let me know once you update if you are having the issue.

**Comment by SubjectHawk66** [comment]
Ok but when will the update be

**Comment by whatthedrunk** [comment]
its up

**Comment by SubjectHawk66** [comment]
Alright cool now I can finally use mek for that stuff again without getting annoyed
