### ISSUE TITLE
Enhancement: Adding recipes to crusher or enrichment chamber

### ISSUE THREAD

**Issue by SubjectHawk66** [AllTheMods/ATM3-Remix#293]
## Detailed Description
I was just looking at recipes for making blizz/blaze/blitz/basalz into its corresponding dust but there's no mekanism recipe, or even actually additions ones for the TE rods, and I think it'd be better to add more compatibility with all mods since mekanism, AA, TE, and EIO are all somewhat "starting" tech mods. Although at the moment, my only suggestion is adding TE rods and blaze rods' corresponding dust recipes to Mekanism machines

Edit: I've also noticed the clathrate cannot be processes in the enrichment chamber and I think it really should.

**Comment by Ki-Tan2934** [comment]
Make a new issue if this is still a problem
