### ISSUE TITLE
Mekanism version is bugged

### ISSUE THREAD

**Issue by Elijah0331** [AllTheMods/ATM3-Remix#294]
Induction Matrix does not work properly. When building a Mekanism Induction Matrix regardless of size or tier it will not store over 2.14GRF. The Dev has confirmed it is a bug within the Mekanism version 9.8.1. The issue was resolved in the update 9.8.2 for Mekanism.

1. Build any size Induction Matrix using "Induction Casing", "Induction Port", "Basic/Advanced/Elite/Ultimate Induction Cell" and "Basic/Advanced/Elite/Ultimate Induction Providers"
2. The GUI will never display over 2.14GRF storage

The issue can be fixed by simply updating the Mekanism mod to the 9.8.2 version.

**Comment by whatthedrunk** [comment]
updated in new beta out soon
