### ISSUE TITLE
Normal Sky Dimlets are Blacklisted

### ISSUE THREAD

**Issue by Leurak** [AllTheMods/ATM3-Remix#295]
Normal Sky, Normal Day and Normal Night Dimlets are all blacklisted.

There are crafting recipe overrides for all non-normal Sky Dimlets, but the Normal ones are blacklisted.

Considering the only alternative to Normal Day is Dark Day and the only alternative to Normal Night is Bright Night, I would be forced to leave this randomized or actually swap the lighting.

## Expected Behavior
Being able to craft and use those dimlets.

## Current Behavior
I am able to craft the dimlets using the recipe in JEI, but they are stating to be blacklisted. Hence I can't use them to actually build dimensions.

However, the dimlets are available for cheating in JEI without being blacklisted. Just the crafting recipes are. Therefore my current solution is to craft the item, delete the blacklisted one and manually cheat a working item.

## Possible Solution
Fix the recipes to yield the proper, unblacklisted dimlets. Maybe also tweak the crafting recipe to fit with the others.

## Steps to Reproduce
Try to craft one of the mentioned dimlets and look at the item description.
![image](https://user-images.githubusercontent.com/18459800/67784223-b8c6ed00-fa6b-11e9-9337-ad5dbc63cbf2.png)

**Comment by whatthedrunk** [comment]
This does not seem to be blacklisted in 1.5.3 coming out later today. Reopen if you still have the issue.
