### ISSUE TITLE
Ender IO Conduits

### ISSUE THREAD

**Issue by Unknownmephi1** [AllTheMods/ATM3-Remix#297]
## Expected Behavior
values of conduits should match the actual throughput

## Current Behavior
Ender IO conduits are capped to roughly 1k rf/t

## Steps to Reproduce
Energetic silver  conduit (Should be 10k rf/t)
Enhanced conduit (should be 5k rf/t)

Both are showing correct numbers but the throughput is somehow capped to 1k tf/t
used 11 Hv solar arrays, connected to conduits (as mentioned above) 1 power cell (5k) and 1 Energy Cell (Reinforced) both wont charge from the mentioned conduits (powerdrain is higher than 1k rf/t) but less than 10k rf/t (Energetic silver)

**Comment by Glendening** [comment]
Unable to reproduce
Hooked up conduits specified between a creative energy bank and an upgraded energy cell. Tested power transfer was what conduits list. Did the same between 11 HV solar arrays on conuits hooked to the energy cell. Saw the same expected power flow.

Are you sure the energy cell you are using hasn't had its input turned down to 1k RF?

**Comment by Unknownmephi1** [comment]
it seemed a client side issue. now its working here. (only change is that the client has been restarted)
Sorry for the inconvenience.
