### ISSUE TITLE
Some missing Forestry Recipes

### ISSUE THREAD

**Issue by mrivnak** [AllTheMods/ATM3-Remix#298]
Several recipes in forestry are missing.
- Hardened, impregnated, and flexible casings
- all circuit boards and electron tubes
- portable analyzer

Using ATM3-Remix v1.5.1 with Forestry 5.8.2.393

**Comment by Glendening** [comment]
All these items are working and craftable however I believe they do not show up in JEI due to how the forestry crafters like the carpenter display recipes.

**Comment by Sakata-MC** [comment]
Also, the default JEI settings have a bunch of stuff hidden in JEI... like stone.
click wrench in JEI and turn on the hiding mode, right click on items that shouldn't be hidden but are (tinted red)

**Comment by whatthedrunk** [comment]
They seem to be working in my test for 1.5.3 coming out later today.
