### ISSUE TITLE
Binnie's Compartment causing a freeze

### ISSUE THREAD

**Issue by fightmesun** [AllTheMods/ATM3-Remix#299]
Pretty much the title says it all. Placed the diamond compartment down and when I left clicked it, the game froze. It doesn't crash until I try to close the program. Tried to see if it was the same issue with the other compartment. Copper froze too. 

## Expected Behavior
Game continuing to function and be able to fully use the compartment block.

## Current Behavior
Game freezes as soon as the compartment GUI pops up. 

## Steps to Reproduce
1. Place any of the compartment block from the Binnie mod into the world
2. Left click or whatever you do to open the gui
3. Game freeze

## Log
https://gist.github.com/fightmesun/5c29aec63b748c05301f71b09a67d7c9

**Comment by whatthedrunk** [comment]
seems to work fine in 1.5.3 coming out later today.
