### ISSUE TITLE
Config Change: Disable Sticky Ore.

### ISSUE THREAD

**Issue by KaneHart** [AllTheMods/ATM3-Remix#30]
aroma1997/aroma1997sdimension.cfg

`B:enableStickyOre=true`
to
`B:enableStickyOre=false`

**Comment by Yoosk** [comment]
But why? I like that way of getting slime balls.

**Comment by KaneHart** [comment]
It can stay I personally think it might just offer to easy of a way to obtain them. Then again there is more slime creatures and methods to get slime type products to begin with. So it might be a simple case now of there is so many sources why produce another one taking up world gen.

That being said it's really not that big of a deal. I found like 5 clusters in the first 10 minutes of mining and oddly enough I have yet to see one again since.  

There is clay ore too kind of odd as there is also normal clay mixed. So it's more of a suggestion / just thought I bring it up but it's not a OMG DISABLED IT NOW! lol

**Comment by OrdinatorStouff** [comment]
I agree with @Yoosk there is no problem with Aroma's dim having clay and sticky ores.
