### ISSUE TITLE
Inability to create Bauble Cosmetic Overrides.

### ISSUE THREAD

**Issue by V2LenKagamine** [AllTheMods/ATM3-Remix#302]
## Expected Behavior

Combining a Bauble with a Botania Cosmetic bauble override should result in the bauble with the cosmetic applied.

## Current Behavior

Combining said Baubles produces no item, as if there were no crafting recipe.

## Steps to Reproduce

1. Take 2 Baubles, 1 of any bauble, 1 of the Botania Cosmetic Baubles (EX: Manaseer Monocle &  Gluttony Charm.)
2. Attempt to combine said items in any crafting table, vanilla or modded.

**Comment by Ki-Tan2934** [comment]
Make a new issue if this is still a problem
