### ISSUE TITLE
Tech reborn Alloy furnace produces TR version of Bronze/Electrum and doesn’t support most alloys

### ISSUE THREAD

**Issue by ixanza** [AllTheMods/ATM3-Remix#303]
The tech reborn Alloy Furnace only makes IC2 bronze and some other alloy. There’s no unification and it is missing a lot of alloy recipes found in nuclear craft/thermal expansion/ender io

## Expected Behavior
Alloy furnaces should be unified among all the mods

## Current Behavior
Alloy furnace from tech reborn has barely any alloy recipes

## Possible Solution
Add proper alloy recipes

## Steps to Reproduce
1. make alloy furnace
2. try to make bronze
3. get IC2\tech reborn bronze instead of thermal bronze 

## Detailed Description

I have a rudimentary script that makes the output only thermal expansion stuff and i've added support for the other alloys following the induction smelter and the nuclearcraft alloy furnace if you'd like to take a look
https://pastebin.com/jLDztjmZ

**Comment by whatthedrunk** [comment]
it outputs thermal in my 1.5.3 test that will be out later today. If you are still having issues please reopen after update.
