### ISSUE TITLE
Rendering item crash: extrautils2:compressedcobblestone

### ISSUE THREAD

**Issue by ArmageddonX430** [AllTheMods/ATM3-Remix#304]
## Expected Behavior
It to not crash.

## Current Behavior
It crash.

## Possible Solution
No idea.

## Steps to Reproduce
1. Place 9 stacks of cobblestone into tinker's crafting table.
2. Cursor-claim stack of compressed cobblestone and drag back across crafting frame to place 7 compressed cobblestone into each location with one remaining on cursor.
3. Program hangs at this point and rendering item crash shows up in crash log.
4. Forcibly shut down hung java client.

## Log
https://gist.github.com/ArmageddonX430/126347a3c1aa3aed7c7215d34bb58598

## Detailed Description
Make no more crash?

Honestly this might be a non-reproducible bug.  I just did a Googer search and couldn't find anyone else having this issue; which is why I wanted to post the issue.  So there's at least some record of it for people to see.  Feel free redirect this issue to Extra Utilities 2 or simply close the issue if you like.

**Comment by Ki-Tan2934** [comment]
Make a new issue if this is still a problem
