### ISSUE TITLE
Kicked from server when Wireless Crafting Terminal is in inventory

### ISSUE THREAD

**Issue by Lasobi** [AllTheMods/ATM3-Remix#305]
The moment a Wireless Crafting Terminal enters my inventory my client disconnects from the server.

## Expected Behavior

Game should continue as normal

## Current Behavior

Server disconnects client.
Reconnecting results in "Connection Lost
Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer"

## Possible Solution

Removing WCT makes it possible to rejoin server.
Might be server related issue as creative single-player works fine.

## Steps to Reproduce

1. Get or make WCT
2. Disconnect
3. Never reconnect unless admin removes WCT
4. Reconnect

## Log

https://gist.github.com/Lasobi/2dae9ff56c6898d71b289dd6051418ac

**Comment by whatthedrunk** [comment]
Works fine in new test build expect beta soon
