### ISSUE TITLE
Unable to complete "a fiery projectile" from Thaumcraft

### ISSUE THREAD

**Issue by DarkDon** [AllTheMods/ATM3-Remix#308]
## Expected Behavior
Get hit either by : Ghast Fireball, Blaze, Fire Charge get unlock research in medium: projectile

## Current Behavior
Can get hit without armor charms etc. still no unlock in thaumonomicon

## Possible Solution
dunno you are the expert, maybe something wrong with the fireball? Maybe NetherEx dunno.

## Steps to Reproduce
1. get hit by Blaze , Ghast, FireCharge 
2. No unlock

Thaumonomicon:
https://gyazo.com/6a0bee7835ee476ba8992e5b6ec8e635

https://gyazo.com/c5334d282bb88b9958dda1d670925311

**Comment by HHServers** [comment]
change "replaceVanillaFireballs" to false in ebwizardry config

https://github.com/AllTheMods/ATM3-Remix/issues/310

**Comment by whatthedrunk** [comment]
fixed in next version expect beta soon
