### ISSUE TITLE
1.5.1 crashing by contenttweaker UPD: 1.5.2 crashing by armoryexpansion

### ISSUE THREAD

**Issue by joinmod** [AllTheMods/ATM3-Remix#309]
## Expected Behavior
start up and show main menu

## Current Behavior
crashing

## Possible Solution
by logs he trying get my videocard or what he is trying to do? (ReflectiveTypeAdapterFactory) 

## Steps to Reproduce
1. open ANY launcher (jar or original launcher from twitch)
2. launch ATM3 remix
3. PROFIT

## Log
https://gist.github.com/joinmod/aae224641188b2704be87abf3f98a8fc

## Detailed Description
tried java 1.8.0-231 and by twitch 1.8.0-51 (all 64bit)
and tried forge 14.23.5.2847 and 14.23.5.2844

P.s
just in case sorry for my bad english

**Comment by joinmod** [comment]
update 1.5.2 fixed the problem

**Comment by joinmod** [comment]
miss click

tested in 1.5.1 and 1.5.2

**Comment by Ki-Tan2934** [comment]
Make a new issue if this is still a problem
