### ISSUE TITLE
Change Electroblobs replacing vanilla fireballs

### ISSUE THREAD

**Issue by HHServers** [AllTheMods/ATM3-Remix#310]
https://www.reddit.com/r/Thaumcraft/comments/dtrz68/issue_caused_by_electroblobs_wizardry/

EBWizardry affects Thaum advancement

ebwizardry.cfg

    B:replaceVanillaFireballs=true
to
    B:replaceVanillaFireballs=false

**Comment by whatthedrunk** [comment]
fixed in next version expect a beta soon
