### ISSUE TITLE
instantly dying from jumping down small height jumps, randomly taking fall damage when sprintjumping, etc

### ISSUE THREAD

**Issue by AdovinOFFICIAL** [AllTheMods/ATM3-Remix#311]
## Expected Behavior

not instantly die from falls

## Current Behavior

small height jumps like 5 blocks, i expect some damage of course but not my entire health bar going all the way down to only half a heart. other times im just sprint jumping and i take half a heart of damage randomly. and i was in the water one time and i just instantly died randomly, and my friend on the other side of the world died as well randomly at the same time as me, both from fall damage?

edit: and also to add on, my friend is using multi-jump and jumped onto a higher area and took fall damage and died instantly? doesn't make sense.

## Possible Solution

no clue

## Steps to Reproduce

1. i installed optifine, webdisplay mod for playing youtube videos ingame on a screen block, flux networks, veinminer, and i removed classic bars and ore excavator, but i dont think any of these things have anything to do with fall damage. difficulty is set to hard
2. just jump off something that would normally only give you a couple hearts of damage
3.
4.

**Comment by Glendening** [comment]
Are you wearing Ender IO Dark steel or other similar Ender IO boots when this happens?

**Comment by Ki-Tan2934** [comment]
Make a new issue if this is still a problem
