### ISSUE TITLE
Lost tablet not awaking in Corail Tombstone

### ISSUE THREAD

**Issue by Draconox99** [AllTheMods/ATM3-Remix#312]
## Expected Behavior

Lost tablet should awake to a location

## Current Behavior

In version 3.6.2 the meta data for the cooldown time of the lost tablet keep increasing indefinitly

## Possible Solution

Update to 3.6.3, got fixed 
https://github.com/Corail31/tombstone_lite/issues/103

## Steps to Reproduce

1.Go fishing and get unlucky to get a lost tablet
2.Check meta data by F3 + H thanks to actually additions
3.Ctrl + Shift on a tablet in your inventory
4.See the meta data cooldown increasing very slowly

**Comment by Ki-Tan2934** [comment]
Make a new issue if this is still a problem
