### ISSUE TITLE
End Cities Crashing Server With Exception Ticking World

### ISSUE THREAD

**Issue by Ashtapada** [AllTheMods/ATM3-Remix#313]
## Expected Behavior

You should be able to find end cities with items in all of the chests

## Current Behavior

If the server loads an end city it will crash, and when restarted any items in the chests will be gone and the city will be pissing peices

## Steps to Reproduce

I'm not quite sure how to reproduce it but I can say that I was running a server before the update that would load end cities jut fine, but when I made a new server with the most recent update is when it started crashing

## Log

https://gist.github.com/Ashtapada/d25f738e98024b3a5e00d3dffc1d0630

## Detailed Description

You could be exploring in the end looking for an end city and just crash from one being loaded in by the server even before you can see it.

**Comment by Ashtapada** [comment]
I have tried resetting the end 3 seperate times aswell as using a chunkloader mod but if any new end cities are found the server will crash, and any loaded cities have completely empty chests.

**Comment by Ki-Tan2934** [comment]
I get the same when player fast generate end city "CHESTS"
##Log
https://pastebin.com/w4Qan2xT

**Comment by flyingmoose** [comment]
Same problem

**Comment by whatthedrunk** [comment]
Looks like it was fixed when I updated to the newest version that came out 2 days ago. 1.5.3 will be out today.
