### ISSUE TITLE
Mekanism machine issue

### ISSUE THREAD

**Issue by Levitikan** [AllTheMods/ATM3-Remix#314]
When making dust in either the crusher or enrichment chambers  it is making dust from various mods for each ingot i.e lead is from Industrial craft 2, gold is from mekanism, which means they are unusable in crafting recipes when turned into ingots as most recipes no longer seem to use ore dictionary. only thermal expansion ingots seem to be accepted for most mod recipes

**Comment by PeteSmith84** [comment]
You can overcome this using drawers with the Conversion Upgrade (as long as you have one of the desired ingots already in there).

**Comment by whatthedrunk** [comment]
This should be fixed in 1.5.3 coming out later today.
