### ISSUE TITLE
binnies extra trees with ULTIMATE bushes

### ISSUE THREAD

**Issue by joinmod** [AllTheMods/ATM3-Remix#315]
## Expected Behavior
the first right click on the leaves should pick 2 berries
the second right click on the same leaves should do nothing
## Current Behavior
a INFINITE berries

## Possible Solution
mayby bug, wrong settings in config or something

## Steps to Reproduce
1. just multiple right click on bush leaves
2. profit

## Log

i think this problem dont need logs

## Detailed Description
here is a [gif](https://imgur.com/j1uoHKR) with a bug demonstration on imgur:

**Comment by Jakaya0897** [comment]
+1 Very jarring and as a server owner unable to resolve at present would like to see a hotfix or config for this behaviour for 1.12.2

**Comment by Ki-Tan2934** [comment]
Make a new issue if this is still a problem
