### ISSUE TITLE
when right clicking to equip EnderIO darksteel armor from the hotbar, the upgrades present on the armor piece are duplicated

### ISSUE THREAD

**Issue by littlejonn3490** [AllTheMods/ATM3-Remix#318]
## Expected Behavior

I would expect the armor piece to equip to its slot and not duplicate the upgrades

## Current Behavior

The armor piece is equipped and all of the upgrades are duplicated 

## Steps to Reproduce

1.Get a piece of darksteel armor with any number of upgrades on it, I used boots
2.Put the piece of armor in a hotbar slot and select it so it is in your hand
3.Make sure the armor slot is empty for the selected piece
4.Right click to equip the armor into the slot and all of the upgrades should duplicate. This can be repeated any number of times

**Comment by ixanza** [comment]
This is an issue on Ender IO's end.
Issue is already reported : https://github.com/SleepyTrousers/EnderIO/issues/5262

**Comment by Ki-Tan2934** [comment]
Make a new issue if this is still a problem
