### ISSUE TITLE
End City Loot Error

### ISSUE THREAD

**Issue by kadenscott** [AllTheMods/ATM3-Remix#319]
While exploring end cities, loot does not generate in chests. Here's the error that appears in console:

## Expected Behavior

Loot generates in End City chest

## Current Behavior

Loot does not generate in End City chest

## Possible Solution

Whatever this is, it seems to be throwing the error:
`com.minerarcana.floralchemy.loot.LootFunctionCrystalthorn.func_186553_a(LootFunctionCrystalthorn.java:29)`

## Steps to Reproduce
https://files.catbox.moe/yuoy7t.mp4
1. Generate End City
2. Find loot chest

## Log

https://gist.github.com/kadenscott/df5fe5627affc34222549a38c0a13880

**Comment by kadenscott** [comment]
Removing Floralchemy server-side fixes the issue.

**Comment by Simber1** [comment]
This is the same issue as #313 which is fixed in 1.5.3.

**Comment by Ki-Tan2934** [comment]
Fixed in 1.5.3
