### ISSUE TITLE
Strange Mining Biome (Aroma) Gen

### ISSUE THREAD

**Issue by Leucetius** [AllTheMods/ATM3-Remix#32]
I'm playing with the actual github Master snapshot with todays commits by Ord and Yoosk integrated manually. Travelled to Aroma's dimension and got a weird gen.

## Expected Behavior
Aroma's Dimension as we know it.

## Current Behavior
Got (lava) lakes all over the place
[https://imgur.com/a/pjwc6pD](https://imgur.com/a/pjwc6pD)

## Steps to Reproduce
1. Get current master *.zip
2. Integrated the last 4 commits of dev manually
3. Travel to Mining Dimension

Edit: I reverted Ord's changes but the dimension looks the same.

**Comment by ShaneCourtrille** [comment]
This may be a planned change in response to concerns over people living in the Mining World raised on Discord..?  Even if it's a bug though  love it.. easy source to Lava but it requires more manual maintenance as pools dry up..
