### ISSUE TITLE
ATM3R 1.5.2 shows 1.5.1 in PackCrashInfo manifest

### ISSUE THREAD

**Issue by jmyoung** [AllTheMods/ATM3-Remix#320]
`config/bloodymods/packcrashinfo.cfg` has;

```S:modpackVersion=1.5.1```

## Expected Behavior

Version should be 1.5.2 instead.  Minor issue of course, but it does make reading the crash log have a point of confusion in it.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by whatthedrunk** [comment]
Fixed in version 1.5.3 coming out later today.
