### ISSUE TITLE
Enderio Omnivoirs and Endervoirs not able to create infinite water sources

### ISSUE THREAD

**Issue by greennd** [AllTheMods/ATM3-Remix#323]
## Expected Behavior
When using one endervoir or 3-4 omnivoirs in the correct orientation it should create an infinite water source, but this does not happen.

## Current Behavior
It just drains the omnivoir or endervoir until there is no water left.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by bomber12309** [comment]
they work as intended, i think you just got mixed up on their function :)
the endervoir is infinite water, but you have to use at least 3-4 endervoirs to make an infinite water source (3 works but is sometimes unreliable. a 2x2 pattern is a better option).
the omnivoir is just a regular tank, it will not make infinite water or anything special, it just stores fluids
