### ISSUE TITLE
Mob Chunks are not obtainable

### ISSUE THREAD

**Issue by Noctleigh** [AllTheMods/ATM3-Remix#325]
## Expected Behavior
When I kill mobs, they should have the possibility of dropping Mystical Agriculture mob chunks. When you hover over the item in JEI, it looks like there should be a % chance a mob chunk will generate, lowering by tier.

## Current Behavior
Mobs are not dropping mob chunks at the rate advertised.

## Possible Solution
1. Create a crafting recipe for the Tier 1 Mob Chunk that includes a drop of each of the mobs from Tier 1. Same thing for all of the tiers above.
2. Find out why the mobs aren't dropping these chunks.

## Steps to Reproduce
1. Hunt a zombie.
2. Kill said zombie.
3. Cry when you've murdered about 100 of these and you still don't have a mob chunk.
4. Re-evaluate your life choices.

## Log
No Log

## Detailed Description
Not an enhancement request.

**Comment by bomber12309** [comment]
You need to use a soul(ium?) dagger for
mob chunks, regular weapons aren't meant to drop them

**Comment by Noctleigh** [comment]
> You need to use a soul(ium?) dagger for
> mob chunks, regular weapons aren't meant to drop them

You are absolutely correct. It was not in the JEI and I wasn't able to find reference of it in any of the books in the akashic tome. Additionally, since this is a new version of the mod, I wasn't able to find any documentation on how to get them.

Please close this issue out.
