### ISSUE TITLE
F7 Lighting button causes crash in local server

### ISSUE THREAD

**Issue by Mstori** [AllTheMods/ATM3-Remix#327]
Pressing the default F7 key to show the lighting markers for light levels causes the game to crash in my local server. Happens every time with me and my friends. Server does not crash. The key is not conflicting with another one.

## Expected Behavior
Supposed to show light markers on the ground for light levels.

## Current Behavior
instant game crash

## Steps to Reproduce
1. join server
2. Click F7 (or the key for light marker levels)
3. Profit

## Log
[crash log](https://gist.github.com/Mstori/c333cca16ab072f0ea2872add2dc9cff)

**Comment by Ki-Tan2934** [comment]
Unable to repeat the steps try removing optifine if you use it and turn off vbos
