### ISSUE TITLE
Crash due to extratree (server side)

### ISSUE THREAD

**Issue by beaussan** [AllTheMods/ATM3-Remix#328]
## Expected Behavior

Should still work

## Current Behavior

Server crash :(

## Steps to Reproduce

I don't know how to reproduce. One people on the server started to do bees, butterfly and tree breading, it's started since they did trees.

## Log

[Crash reports](https://gist.github.com/beaussan/59a30c57a0427f5d48db46adc814be48)

**Comment by Ki-Tan2934** [comment]
Forestry Is the cause restore from a backup if you can
