### ISSUE TITLE
Wizardry spellforge's codex not loading properly

### ISSUE THREAD

**Issue by Levitikan** [AllTheMods/ATM3-Remix#329]
Playing through the wizardry mod and noticed some text popping up when opening it that says the book has not loaded properly. 
ATM 3:Remix V1.5.4

## Expected Behaviour
the book should open normally and all the necessary information should be there including unlocked information

## Current Behaviour
It looks like a lot of the information is missing as it comes in red text "the book didn't load correctly..."

screenshot of the problem
https://prnt.sc/r99tu8

## Steps to Reproduce
1. Select spellforger's codex in the akashic tome.
2.Open the book

**Comment by Ki-Tan2934** [comment]
This should be reported to the mod developer
