### ISSUE TITLE
Fluid Cells Larger than 256K do not work

### ISSUE THREAD

**Issue by Arudinne** [AllTheMods/ATM3-Remix#330]
## Expected Behavior
Fluid Cells of any size should be able to store Fluid within an AE2 network on ATM3R 1.5.3.

## Current Behavior
I built an AE2 system with 60 4096K fluid Cells but the system was unable to import ANY liquid even vanilla water. Once I dropped in some 64K and 256K cells the system worked as expected. No other Cells (Gas, Items) appear to have problems

## Possible Solution
Update AE2 from RV5 to RV6.

More details here:
https://github.com/ExtraCells/ExtraCells2/issues/684

**Comment by Ki-Tan2934** [comment]
AE2 is V6 stable 7 update your pack version
