### ISSUE TITLE
Dimensional Shard Seeds duplicating when harvested

### ISSUE THREAD

**Issue by turret001** [AllTheMods/ATM3-Remix#331]
## Expected Behavior
They should only drop dimensional shard essence only.

## Current Behavior
Dimensional shard seeds give Dimensional Shard Seeds as byproduct when harvested by Cyclic harvester. Not sure if normal harvesting does this as well

## Possible Solution
/shrug

## Steps to Reproduce
1. Plant Dimensional Shard Seeds
2. (optional) add 40 growth accelerators under it
3. (optional) place greeenhouse glass above the plant (from actually additions mod)
4. set a 15x15 area harvester (from cyclic mod)
5. wait for the harvest!

## Log
N/A

## Detailed Description
-

**Comment by Ki-Tan2934** [comment]
Think of this as a feature
