### ISSUE TITLE
Tech Reborn's implosion compressor multiblock not completing

### ISSUE THREAD

**Issue by Sinuboh** [AllTheMods/ATM3-Remix#333]
The implosion compressor has a hologram for its multiblock and on completing the hologram the multiblock will not complete and the implosion compressor remains inactive

## Expected Behavior
Multiblock forms
Implosion Compressor works

## Current Behavior
Multiblock does not form
Implosion Compressor does not work

## Possible Solution
Potentially updating the build of TR to a newer 1.12.2 version might fix this as this is similar to an issue posted on their github

## Steps to Reproduce
1. Implosion Compressor (Tech Reborn)
2. Attempt to complete multiblock
![2020-04-07_10 50 00](https://user-images.githubusercontent.com/63311496/78702524-9314fe00-78bd-11ea-83b0-a33a48b3d352.png)
![2020-04-07_10 50 05](https://user-images.githubusercontent.com/63311496/78702536-990adf00-78bd-11ea-84cc-0342fe3bbc34.png)

**Comment by Ki-Tan2934** [comment]
Will be updating the pack soon make a new issue if the problem occurs
