### ISSUE TITLE
Machine Reader from Integrated Dynamics not reading Temperature related field on NuclearCraft properly

### ISSUE THREAD

**Issue by cdterrell2** [AllTheMods/ATM3-Remix#335]
## Expected Behavior
I expect that the temperature field(s) should rise with the temperature output of the Fission Controller, but it does not.

## Current Behavior
The double field that represents most of the temperature related fields does not respond when the machine contains heat.

## Possible Solution
Requires research.

## Steps to Reproduce
1. Set up a Fission Reactor that generates excess heat to make progress towards a "meltdown."
2. Attach a Machine Reader from Integrated Dynamics to the Fission Controller.
3. Attach at least one logic cable to the Machine Reader to access the Machine Reader.
4. Activate the reactor (by redstone signal) to generate heat. Quickly observe the Machine Reader variable "Temperature" is not increasing.

## Log
No logs to post, game does not crash.

## Detailed Description
Suggested change is to have the Temperature related fields on the Machine Reader increase when there is Heat within the machine block.

**Comment by Ki-Tan2934** [comment]
This should be reported to the mod developer
