### ISSUE TITLE
Induction matrix doesnt update power stored

### ISSUE THREAD

**Issue by Felonster** [AllTheMods/ATM3-Remix#336]
## Expected Behavior
Induction Matrix update power stored when above 2.14grf

## Current Behavior
Induction matrix doesnt show power stored and it doesnt update power storage when power storage is above 2.14grf, but still insert and store power

![image](https://user-images.githubusercontent.com/63251332/81191484-5c63fd80-8fb9-11ea-8015-3a8ba7d21e40.png)

**Comment by Ki-Tan2934** [comment]
This should be reported to the mod developers github
