### ISSUE TITLE
Game crash, when port or travel to my base

### ISSUE THREAD

**Issue by benjiben55** [AllTheMods/ATM3-Remix#338]
## Expected Behavior
dont crash

## Current Behavior
game crasg to desktop after port or travel to my base.

## Possible Solution
i dont know :)

## Steps to Reproduce
start game and travel or port to my base, then crash to 60%...

## Log
https://gist.github.com/benjiben55/1e5c6d4e4bea2ada2f2234e3be7bd60f

## Detailed Description
I add some mods but the game crash with and without the new mods.

Thanks for help

benjiben55

**Comment by Ki-Tan2934** [comment]
possible due to extrautils2 sound dampener
