### ISSUE TITLE
[0.0.3] Iron Plate Crafting Issues.

### ISSUE THREAD

**Issue by KaneHart** [AllTheMods/ATM3-Remix#34]
The 2 biggest issues
- there is a cheap recipe of 3 iron ingots to 3 iron plates: https://i.imgur.com/ucHP2fq.png
- there is no IC2 Hammer recipe to make Iron Plates.

Tin/Copper seem fine so far but the Iron one seemed quite wacked out.

**Comment by Yoosk** [comment]
Unidict went crazy with those.
