### ISSUE TITLE
The Tinker's Construct armor tab

### ISSUE THREAD

**Issue by Bam138** [AllTheMods/ATM3-Remix#340]
When I play the game I don't see the armor tab for Tinker's where it should be and when I press the "o" button for it it doesn't work.

## Expected Behavior

When you go into your inventory it should appear at the top of the hud. 

## Current Behavior

The tab does not appear

## Steps to Reproduce

1. press e for inventory 
2. look top of hud where it should be
3.
4.

**Comment by Ki-Tan2934** [comment]
You are looking for Construct's Armory
