### ISSUE TITLE
Random Crashes due to insufficent ram

### ISSUE THREAD

**Issue by Danielek0125** [AllTheMods/ATM3-Remix#341]
## Expected Behavior

I expect not to get random crashes.

## Current Behavior

I just play and suddenly Minecraft either starts flickering and crashing or just crashes like if it was killed.

## Possible Solution

I don't know how to fix this. I started with 7gb but i got the crash so i tried to give it a little bit more each time and it ended up with 11gb but still saying insufficient ram. I have a friend playing on the same server but he gets none of these issues.

## Steps to Reproduce

As is said Minecraft crashes randomly (I think) so i don't have any steps to reproduce or screen captures. When i try to make a screenshot i crash before i get any screenshot.

## Log

https://gist.github.com/Danielek0125/d705a293f13cc2ce29d0b976d0e1234a

## Detailed Description

Sometimes when Minecraft crashes it also kills some windows programs e.g. the desktop background or icons. I also saw that Discord tends to crash Minecraft so i keep Discord off. When fullscreen mode is on Minecraft tends to crash more often and also black out my second screen and getting extremely low fps. I got a weird artifact after which Minecraft crashed but i couldn't get a screenshot of it like i said above.

The was in Nether and it looked like a little bit like if i reached the edge but when i turned so i barely could see the artifact it showed the rest of the Nether and when i turned back the artifact came back.

**Comment by Ki-Tan2934** [comment]
Possible memory leak or you cpu, ram, or gpu is dying

**Comment by Danielek0125** [comment]
What do you mean by cpu or gpu is dying? And i don't know what could leak my memory when i keep all other programs closed.
