### ISSUE TITLE
ATM3R is crashing when I start it. v1.6.0.

### ISSUE THREAD

**Issue by Siydge** [AllTheMods/ATM3-Remix#343]
## Expected Behavior
The game should load fine.

## Current Behavior
Clicking Start on the Launcher starts it, and then half way thru the loading bar on the launcher it just freezes and crashes.

## Steps to Reproduce
1. Download V1.6.0
2. Start it.
3. It would crash.

## Log
https://gist.github.com/Siydge/38b2ff0223309d02b6a8b0348b01d290

## Detailed Description
I am running Windows 10 Home with Ubuntu Booting aswell, although I am playing Mineraft on Windows
Specs: GPU: GTX 1660, CPU: Ryzen 5 3600, Motherboard: MSI B450, RAM: 2x8 Corsair Vengeance
This issue occured right after the latest update, previously older versions had worked fine, but v1.6.0 instantly crashes it.

**Comment by Ki-Tan2934** [comment]
Try reinstalling or using a different mod launcher.
You may need to reinstall or rollback your graphics driver for Nvidia, removing splash animations may work for you.
