### ISSUE TITLE
Tech Reborn Rubber Log not showing in JEI

### ISSUE THREAD

**Issue by K9-guardian** [AllTheMods/ATM3-Remix#344]
# Expected Behavior

Tech Reborn Rubber Logs should show up in JEI.

## Current Behavior

They don't.

## Possible Solution

Most likely an issue with JEI thinking the logs are a duplicate of ic2 rubber logs and thus hiding them.

## Steps to Reproduce

1. Open Inventory
2. Type "@techreborn rubber wood"
3. JEI is empty

## Log

Not a crash so no log

## Detailed Description

Make a new plugin or use an existing one and edit the ISubtypeRegistry to register the logs as unique.

**Comment by Trinsdar** [comment]
Why would tech reborn rubber logs be unique? They are litterly just rubber logs, i see no reason for duplicates. Also did you actually mean to post this in the tr repo? Cause you have under the detailed description what to do in the mod's code, and there is definitely no java here.
