### ISSUE TITLE
Nether ore generation

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM3-Remix#36]
Analyze nether ore generation especially with NetherEx replacing most netherrack with custom blocks. CoFH worldgen can be used to add custom generation entries if needed (eg custom entry to spawn ardite/cobalt into NeX netherrack blocks)

**Comment by SpeedSlider** [comment]
I think nether gen is fine as you have to go searching for regular netherack biomes to mine ores... seems like a good fit with the pack theme.
