### ISSUE TITLE
[3R Full][1.6.0] Nether mobs won't spawn after update

### ISSUE THREAD

**Issue by VexisArcanum** [AllTheMods/ATM3-Remix#362]
I updated my server and client from 1.3 to 1.6 and this initially broke the nether by removing a ton of blocks like gloomy netherrack. I reset the nether by deleting the dimension folder and it regenerated nicely. However no mobs will spawn outside of a nether fortress. I searched everywhere and nothing appears outside the fortresses.

## Expected Behavior

Mobs should be spawning everywhere in the nether. 

## Current Behavior

Mobs in the nether only spawn naturally in fortresses. 

## Possible Solution

I had to copy some configuration files between my old and new client and server but the world folder is just straight up copied without edits. 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Ki-Tan2934** [comment]
The nether needed resetting due to NetherEX update.
