### ISSUE TITLE
[1.12.2][2.0.0] Advanced Rocketry Warp Core Multiblock does not form with the Titanium Blocks from Tech Reborn

### ISSUE THREAD

**Issue by radj307** [AllTheMods/ATM3-Remix#369]
## Expected Behavior
The Warp Core multiblock should form when building it on a space station with the only Titanium Blocks available without cheating.

## Current Behavior
Right-clicking the completed multiblock structure shows a little red 'X' located on the titanium blocks from Tech Reborn.

## Possible Solution
Remove the Tech Reborn titanium blocks and replace them with the titanium blocks from LibVulpes in crafttweaker.
I managed to form it by using the holographic projector to show the warp core multiblock projection, then switching to creative mode and using pick block on the projected titanium blocks, then using them to build the structure.

## Steps to Reproduce
1. Build a space station with Advanced Rocketry.
2. Attempt to build the warp core multiblock using the Titanium Blocks from Tech Reborn (the only ones not removed in crafttweaker).
3. Right-click the warp core block.

**Comment by Silfryi** [comment]
Hi! AR dev here. Can't do the PR offhand right now but there's specific oredicts for the warp core blocks now. `blockWarpCoreCore` and `blockWarpCoreRim`. You should be able to add the second one to the TR titanium blocks for it to work.

**Comment by Pelotrio** [comment]
Someone brought up the same problem on the discord a while ago. After decompiling different versions I found that the oredict changed so the Tech Reborn titanium blocks do not work anymore. I added it manually with crafttweaker and as expected it worked again. Once I make an update for Remix I will reference this issue in a commit. Thank you @Silfryi for pointing out the issue but its still kind of annoying that advanced rocketry just changes something like this.

**Comment by Silfryi** [comment]
I twas to add compat for people changing the warp core to anything they wanted - since you can edit those oredicts, I could make the warp core made of special contenttweaker warp core engineering blocks or something, to give people more freedom.

**Comment by Pelotrio** [comment]
That definitely sounds reasonable but I cant update to any 2.0 version of advanced rocketry anyways as all machines will be broken then. Currently in all versions I can use the oredict is hard-coded so I have to do it with crafttweaker anyways.

**Comment by Silfryi** [comment]
You'd be doing it with CT regardless, but what is your exact problem with 2.0.0? Just the in general stuff that a bunch of machines changed and you can't warn everybody? Or something else specific? There's a _huge_ amount of fixed bugs in 2.0,0 if you do make the jump.

**Comment by Pelotrio** [comment]
Just the trouble of telling everyone that all the machines they ever placed from Advanced Rocketry will be broken in the next update. I had to make the same decision in ATM 3 and thought the bug fixes weren't worth breaking all machines. I haven't really tested it, so I don't know how much has changed for the better. Maybe it's worth upgrading, but I didn't want to last time. I'm currently the only one working on both packages anyway, and they're not the focus of the ATM team anyway, so I'll have to see what I do in the future.  If you have any recommendations feel free to tell me as you probably have more inside on this topic.
