### ISSUE TITLE
SP crashes 

### ISSUE THREAD

**Issue by sndmax** [AllTheMods/ATM3-Remix#42]
## Expected Behavior

I should ride a squids or whatever in a SinglePlayer world

## Current Behavior

Crashing when <del>thinking about squids</del> trying to connect SP world if earlier I was in MP. Works fine when I'm just started client and joined SP.
Have this problem from ATM3 5.x

## Possible Solution

Fix it

## Steps to Reproduce

1. Start the game 
2. Wait...
3. Wait...
4. Wait..
5. Join MP
6. Wait...
7. Disconnect from MP
8. Wait...
9. Join SP
10. Cuss out

## Log

https://gist.github.com/sndmax/d4aef4e0da8de05941cfe73349c82e7e

## Detailed Description

Hello...?

**Comment by sndmax** [comment]
If i can help with something due i have the crash each time switching between MP/SP, let me know.
Discord: om_r#3567

**Comment by FallenEagle1** [comment]
So far I have as well had the issue, so at least it is testable. Problem is, the fixes I have tried in the past nothing works, so need to try and find new fixes to test.

**Comment by BloodWorkXGaming** [comment]
Does it happen when joining a server where there are rftools dimensions
loaded and on a single player World where there aren't?

FallenEagle1 <notifications@github.com> schrieb am Do., 13. Sep. 2018,
15:42:

**Comment by FallenEagle1** [comment]
The one world that I have used in the past is just a flat test world, and never gone to any other dimensions. This is the one that has crashed on me in the past before after leaving a world. Looks like it does deal with rftools in some fashion. https://pastebin.com/aC5h4JqQ

**Comment by Yoosk** [comment]
Tested few times on our dev instance and server, rejoined multiple times from server to SSP without issues. Seems to be fixed.

**Comment by Yoosk** [comment]
Then my game hanged up on leaving server.

**Comment by Yamza** [comment]
I also had this happen a few times last week.

**Comment by Darkere** [comment]
https://github.com/McJtyMods/RFToolsDimensions/issues/205
