### ISSUE TITLE
[0.0.3] Simple Jetpack Creative Jetpack can be created with none ATM Star's.

### ISSUE THREAD

**Issue by KaneHart** [AllTheMods/ATM3-Remix#45]
So you can create The Creative Jetpack with the following items:
Light Radiation Shielding 
Medium Radiation Shielding 
Heavy Radiation Shielding 

With any version of the Simple Jetpacks so even tier 1... 
Example:
https://i.imgur.com/gDaAL5f.png
https://i.imgur.com/6KTZa3o.png

**Comment by FallenEagle1** [comment]
This is an issue with nuclearcraft and is fixed in newer versions of that mod. Leaving open for the moment to remember to update the mod, but itll be fixed.

**Comment by Yoosk** [comment]
We are always updating all mods so that a null to keep it open.
