### ISSUE TITLE
Official "TPS Hog" List

### ISSUE THREAD

**Issue by Yamza** [AllTheMods/ATM3-Remix#51]
If you encounter any thing that causes TPS issues, please report them here. If possible, also provide a description of what it was doing and a log of some sort showing it's tick rate. _Speculation is not helpful._

If you have any logs of the current known issues, please feel free to add them here. The more info provided, the more likely it will be addressed.

For information on how to profile your client or server, please see this guide:
https://www.reddit.com/r/allthemods/comments/9ugu6s/server_profiling/

Known Issues------------------------------------------------
Pushing items into full containers/machines
Mek pipes of all kinds
Networks of EnderIO conduit (all kinds)
Mek Digital Miner (even when not running)
Rftools Builder while running, especially when full
Tinkers Smeltery when over full
Pure Daisy with items in it's range
External Storage (RS) & External Storage Bus (AE2)
Crafting Card (AE2)

**Comment by Yamza** [comment]
Issue created for AA Coal Generator: https://github.com/Ellpeck/ActuallyAdditions/issues/1184

**Comment by Yamza** [comment]
Existing issue for Bonsai Planters: https://github.com/thraaawn/BonsaiTrees/issues/61

**Comment by Shadows-of-Fire** [comment]
I believe FoamFix has a performance patch for the hopper

**Comment by Yamza** [comment]
Looks like the Foamfix patch is enabled already. https://i.imgur.com/1HkgjU3.png

**Comment by Yamza** [comment]
Pure Daisy issue: https://github.com/Vazkii/Botania/issues/2761

Maybe fixed in newer version?

**Comment by PhanaticD** [comment]
Random Tweaks squid handler: https://gyazo.com/b9164f2cf1e958e7956914ea7bcb99bc

**Comment by PhanaticD** [comment]
Random Things time in a bottle causes major lag (+15 ms a tick from just one user having a few in his inventory)

issue reported here: https://minecraft.curseforge.com/projects/random-things?comment=436

**Comment by Yamza** [comment]
@PhanaticD You should put it on their github.

**Comment by Yamza** [comment]
Time in a Bottle issue: https://github.com/lumien231/Random-Things/issues/355

**Comment by Sleeeper** [comment]
TCon Smeltery controller, when full of fluid and having more items with smelted bar full waiting for fluid space, eats up to 6ms

**Comment by xGarionx** [comment]
The Import/Export issue ,seems to halt the entire me system auto-crafting (import export stops and every current crafting shedulded aswell ), including the auto-crafting timer ,the issue seems to occur randomly (at least i didnt see any pattern yet)
