### ISSUE TITLE
/dank/null causes disconnect on switching of active item

### ISSUE THREAD

**Issue by userjjb** [AllTheMods/ATM3-Remix#63]
Switching the active item of a /dank/null causes a disconnect from the server with the error "A fatal error has occur, this connection is terminated".

Switching active item means either from using shift+scroll to scroll to a different item, or opening the /dank/null/ with shift+rightclick and then alt+clicking the desired new active item. Both immediately cause a disconnect with the aforementioned error message.

The /dank/null operates otherwise fine, automatically collecting items, allows you to place the active item (which of course can't be switched now), and allows you to manually deposit and retrieve all items stored in it.

This is new behavior in 0.1.2, it functioned normally in 0.0.3 previously.

**Comment by FallenEagle1** [comment]
Im guessing it is related to p455w0rd/DankNull#138, the mod will be updated in dev
