### ISSUE TITLE
Broken recipes for jetpacks

### ISSUE THREAD

**Issue by Kyub3y** [AllTheMods/ATM3-Remix#65]
## Expected Behavior

Recipe for Conductive/Electrical/Dark Steel armor plating should be available.
Broken recipes with jetpacks from Simply Jetpacks 2 should be removed .

## Current Behavior

No way to craft Conductive/Electrical/Dark Steel armor plating, which is required to craft Dark Soularium JetPlate. 

Broken recipes for creative jetpack in JEI:
any jetpack + Light Radiation Shielding = creative jetpack
any jetpack + medium Radiation Shielding = creative jetpack

When try crafting this 2 recipe, the creative jetpack shows up in the crafting slot but can't be taken.

## Possible Solution

Fix the recipes.

## Steps to Reproduce

1. Search for jetpack in JEI
2. Check the recipes

**Comment by FallenEagle1** [comment]
What version of the modpack? I thought this was fixed already.

**Comment by Kyub3y** [comment]
Ah sorry. Forgot the server I play on haven't update to the latest version yet.
