### ISSUE TITLE
No recipe for dark soularium ingot - ver 0.1.2

### ISSUE THREAD

**Issue by Kyub3y** [AllTheMods/ATM3-Remix#67]
## Expected Behavior
Recipe for dark soularium ingot should be available, since it's required to craft the dark soularium JetPlate.
Correct recipe should be:
In Alloy Smelter:
1 dark steel ingot + 1 pulsating crystal + 1 soularium ingot = 1 dark soularium ingot

## Current Behavior
No recipe for the dark soularium ingot, even though the recipe for the dark soularium JetPlate is available.

**Comment by Yoosk** [comment]
Fix for that issue should be on mod developer, however if we wont get any answer to that https://github.com/AllTheMods/ATM3-Remix/issues/67, i'll add that recipe on modpack side.

**Comment by Yoosk** [comment]
![2018-10-17 16-33-25-javaw](https://user-images.githubusercontent.com/4502802/47093936-7a78da00-d22a-11e8-96da-ed73caca9472.png) Recipe is ready.

**Comment by Kyub3y** [comment]
so this will be in the next update? If so then I'll close the issue.

**Comment by FallenEagle1** [comment]
In one way or another, there will probably be a recipe. Leave open for now so that it is remembered. We'll close it once it is put into dev

**Comment by Yoosk** [comment]
https://github.com/AllTheMods/ATM3-Remix/commit/837f6d84dde92c0174ff1fd79935dc0cda24caa0
