### ISSUE TITLE
Pack Configured Client Tweaks won't allow offhand torch placement.

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM3-Remix#7]
## Expected Behavior
When a torch is in the offhand using the mouse right button will place a torch unless a block is in your offhand.

## Current Behavior
Torch cannot be placed when in the off hand.

## Possible Solution
It appears to be a client tweak pack setting. I say pack setting because if you hit the restore default options then a lot of options change. There is an offhand torch tool setting as well to let you set the tools that will allow torch placement if you are using a tool. This seems like a good tweak, but the defaults are Tinker's Construct shovel and excavator.  It did not appear to work with a wood and stone shovel though. Setting both "No offhand torch with empty hand" and "Offhand torch with tool only" options to default seem to solve the issue. Just disabling the offhand torch with tool only didn't seem to solve it.

## Steps to Reproduce
1. Problems seems simply stated above.
2.
3.
4.

## Log
None

## Detailed Description
Above details fully describe issue :P

**Comment by Yoosk** [comment]
https://github.com/AllTheMods/ATM3-Remix/commit/04ea91b398333a5549b1872545b6b2dbd9c13998
