### ISSUE TITLE
Crash on startup 0.1.2

### ISSUE THREAD

**Issue by ConnCraft** [AllTheMods/ATM3-Remix#75]
Crash on startup.
https://pastebin.com/1ndm9BJ4
Previously had a crash on world loading. Fixed it by swapping in a folder from a backup. Possibly that's the error here? World loaded fine before.

**Comment by DKnightADRI** [comment]
This appears to be a foamfix issue.
Can you try setting this to true in foamfix.cfg?

# Disables all coremod functionality. [default: false]
    B:forceDisable=false

**Comment by ConnCraft** [comment]
It worked. Thank you.
