### ISSUE TITLE
Worm Dupe 

### ISSUE THREAD

**Issue by Ashtapada** [AllTheMods/ATM3-Remix#78]
Using an atm star for crafting the super worm i used the 2x2 crafting in the regular inventory and a stack of each worm i was able to dupe 250k of the regular worms.

## Expected Behavior

it should take 2 worms and the atm star but re drop the star once ive crafted with it along with a single super worm

## Current Behavior

The atm star is dropped after ive crafted the super worm but the worms that I had used to craft it would just double in number.

## Steps to Reproduce

1. Get an atm star, and 2 stacks of the water strainer worms.
2. put them in your inventory crafting area with the star in the top left and the worms on both faces.
3. Just craft the worm and they should duplicate. 
4.

## Detailed Description

https://www.youtube.com/watch?v=tsIzM8zhMlY

**Comment by Yoosk** [comment]
fixed by https://github.com/AllTheMods/ATM3-Remix/commit/9d81f4e1e6ee8eb389256ddd1524ef85ab539fda
