### ISSUE TITLE
Better builders wand recipes give mine colony wands

### ISSUE THREAD

**Issue by dorin6565** [AllTheMods/ATM3-Remix#8]
The recipe for the better builders wands give mine colony wands.  I tried both the stone and iron wands.

## Expected Behavior
The recipe should give the stone or the iron builder wand.

## Current Behavior
I get a mine colony wand.

## Possible Solution
Change one set of formulas to use 2 cobble and a stick or something different.

## Steps to Reproduce
1.  Put 2 sticks and a cobblestone (or iron) in crafting table on a diagonal.
2. It will show a mine colony want instead of a builder wand.
3. Look up better builder wand in JEI and push + and it will give a mine colony wand.

**Comment by Lartza** [comment]
When Minecolonies was supposed to be removed it's scripts were removed and they were never re-added.
https://github.com/AllTheMods/ATM3-Remix/commit/0cbb5cc10dbc03d5a4da0aaa848fa62d390c9b73 for reference

You should be able to craft them using a Forestry Worktable until the issue has been solved.

**Comment by dorin6565** [comment]
Ok thanks, I will give it a try.
