### ISSUE TITLE
Embers Structure Duping

### ISSUE THREAD

**Issue by Ashtapada** [AllTheMods/ATM3-Remix#80]
Using the moving wand from not enough wands you are able to move the center piece of an embers structure and then you can mine the others and it will still drop the structure, if you also move the other pieces away from the others you can also mine those for the drop as well.

## Expected Behavior

If you pick it up with the moving wand it should take the whole structure, or not be able to take them at all.

## Current Behavior

You are able to take a single block of the structure and any others that are mined will drop it as usual but you will still have the piece in the moving wand that can be placed for the full structure again anywhere.

## Possible Solution

Blacklist the moving wand from working on it.

## Steps to Reproduce

1. Get a moving wand, and any embers multiblock structure
2. Use the moving wand on the very center block of the structure, or the spot that it was placed in.
3. Mine the block and you are still able to place it from the moving wand while getting the drop.
4.

## Detailed Description

https://www.youtube.com/watch?v=-jQc4Ixk9r4&feature=youtu.be

**Comment by FallenEagle1** [comment]
Fixed in dev
