### ISSUE TITLE
Shift-clicking item stacks into EU2 machines causes client freeze[EU2]

### ISSUE THREAD

**Issue by Yamza** [AllTheMods/ATM3-Remix#83]
Not consistently reproducible!

Specifically tested on generators.
also: "iron into an enchanter from EU2"

Client becomes non-responsive, does not recover.(Ram spike?)

## Possible Solution
Don't shift-click stacks of items into EU2 machines.

## Steps to Reproduce
Shift-click a full stack of items into an EU2 machine that it should accept.

## Mod List
Modpack: ATM3 - Remix 1.0.0
Minecraft: 1.12.2
Forge: 14.23.5.2768

Extra Utilities 2: 1.9.8

https://github.com/rwtema/Extra-Utilities-2-Source/issues/155

**Comment by JunaidA197** [comment]
The iron crash happened to me when there was already some iron in the enchanter (e.g there was 16 iron and I tried to shift click 64 in)

**Comment by Yoosk** [comment]
Can confirm same thing happened for me, and i highly doubt i can fix that on modpack level.
