### ISSUE TITLE
Dragon Scale Dupe 1.0.0

### ISSUE THREAD

**Issue by JunaidA197** [AllTheMods/ATM3-Remix#84]
Can dupe Quark dragon scales (used to make elytra)

## Expected Behaviour

It should consume the dragonscale

## Current Behaviour

I am manually crafting it in my RS crafting grid, if I take the crafted elytra and put it in the system NOT my invent, I get an equal amount -1 of dragonscales that I had in the grid.
E.g If I had 64 scales in the grid, and made 1 elytra and put it in my system (NOT INVENT) I would receive 63 scales in my inventory.

## Possible Solution

No Clue

## Steps to Reproduce

1. Put 1 elytra and X amount of scales in crafting grid https://i.gyazo.com/e224c7acd1376c57f716bcb2739b0a46.png
2. Take black elytra and put it into RS System (no shiftclicking, just drag)
3. Enjoy your X free dragon scales https://i.gyazo.com/658af9568aa76dac809bb07dbe1f7881.png

**Comment by Yamza** [comment]
Video: https://www.dropbox.com/s/kgy43fb2ybiky9f/2018-11-04_17-36-01.mp4?dl=0
Picture of RS setup: https://i.imgur.com/TRnnBUi.png

## Mod List
Modpack: ATM3 - Remix 1.0.0
Minecraft: 1.12.2
Forge: 14.23.5.2768

Refined Storage: 1.6.8
Quark: r1.5-130

**Comment by Yoosk** [comment]
Fixed by https://github.com/AllTheMods/ATM3-Remix/commit/5f65e19876fa594b3a26ea91b24924ef4df9db41
