### ISSUE TITLE
Dimensional Shard Seeds replicating

### ISSUE THREAD

**Issue by Aeloria82** [AllTheMods/ATM3-Remix#91]
## Expected Behavior

Seeds shouldn't replicate through non crafting means.

## Current Behavior

I ended up with nearly 13k dimensional shard seeds after about 12 hours

## Steps to Reproduce

I planted seed in my garden that is harvested via cyclic harvester, it has about 10 growth accelerators below the farmland.   I am using rustic's fertile soil however only the dimensional shards are replicating.  I also have cyclic sprinklers going.

**Comment by SpeedSlider** [comment]
As an additional note the seeds are identified as from the JAOPCA mod and when using fertilized essence will grow faster but won't give you any crops they just reset. Also, after using fertilized essence and harvested from an AA farmer it gave up the crop but the seed disappeared.

**Comment by lhw** [comment]
This bug popped up again with 1.4.0 its currently generating 3 seeds for every essence.

**Comment by CraXyOW3** [comment]
Can verify that this is a problem in 1.5.1.
Using Actually Additions Farmer and JAOPCA Dimensional Shard Seed.

**Comment by Yamza** [comment]
Unfortunately JAOPCA seeds do not follow the config as the dev says they do, so we cannot fix this issue.

**Comment by Yamza** [comment]
https://github.com/TheLMiffy1111/JAOPCAAgriculture/issues/12
