### ISSUE TITLE
Immersive Engineering wont accept Copper Wire from IC2

### ISSUE THREAD

**Issue by Yamza** [AllTheMods/ATM3-Remix#92]
Jadeonking:
mfw immersive engineering wont accept copper wire from IC2 only likes the wire made from the wire cutters or the multiblock i dont wanna make lol

Ordinator
"Immersive Engineering recipes that need a copper wire will only take IE specific copper wire as ingredients, not the IC2 copper wire item"

**Comment by Yoosk** [comment]
Those two wires and mods are not related to each other, copper wire and copper cable are different things with different costs. It should stay as is.
