### ISSUE TITLE
Quantum Solar panel uncraftable SIMPLIFIED

### ISSUE THREAD

**Issue by krisjenner** [AllTheMods/ATM3-Remix#97]
## Expected Behavior

Quantum Solar panel craftable

## Current Behavior

Quantum Solar panel not craftable

## Steps to Reproduce

1. Try to craft Quantum Solar panel from TechReborn in ATM3 Remix v 1.0.1 Simplified

[screenshot](https://imgur.com/a/Z73ZA1i)

**Comment by FallenEagle1** [comment]
Is this on a server?

**Comment by krisjenner** [comment]
Yes

**Comment by FallenEagle1** [comment]
I would test this in singleplayer, as I'm wondering if this is a script conflict between server and client

**Comment by krisjenner** [comment]
works in SP so i've re-downloaded scripts folder. thankyou
