### ISSUE TITLE
[Bug] Basalt Issues

### ISSUE THREAD

**Issue by ReiDaTecnologia** [AllTheMods/ATM3-Remix#98]
The modpack add several Basalts and i can't convert it to another using Chisel and the Chisel version of it don't have a recipe (I don't know if it generate in the world i never saw it tbh)

## Expected Behavior

One Universal Basalt (I recommend the Chisel) with recipe if possible (Can be WorldGen only if you want)

## Current Behavior

Several Basalts in the modpack (You can't convert to the others using Chisel) and the Chisel basalt don't have recipe.

## Possible Solution

Remove all the basalts that you can get somehow (Like worldgen) and use the Chisel version only and add the basalts in the Chisel config to convert all that basalts to one that you like.

## Steps to Reproduce

1. Search "Basalt" in the JEI and you will see all the basalts.
2. Click to see the recipe of the Chisel (No Recipe).
3. Click to see the use of the basalts, some will not have a conversion recipe using the Chisel.
4. No profit :(

## Detailed Description

If you need more info or something just tell me here or in the Discord :) <3
Edit: I forgot to tell that you can craft Chisel basalt using MA (Mystical Agriculture) but it's not a good way to get it imo.

**Comment by ghatus0** [comment]
Chisel basalt definitely generates naturally but it would be awesome if the projectred basalt could be made with chisel since the volcanos are disabled.

**Comment by FallenEagle1** [comment]
Not all of the worldgen was removed just because of the way they have it in, but they should be chisel-able now.

**Comment by FallenEagle1** [comment]
Update is live with the fix.

**Comment by Yamza** [comment]
This basalt was not added.
https://i.imgur.com/8ycDQjE.png
