### ISSUE TITLE
IllegalStateException error while loading the modpack.

### ISSUE THREAD

**Issue by Mario3264** [AllTheMods/ATM3-Remix#99]
## Expected Behavior

Load flawlessly, even if it loads very slowly due to ram limits.

## Current Behavior

Crashes while loading, doesn't even get to the title screen.

## Steps to Reproduce

1. Open the modpack.
2. Run the game.
3. Let it load for a while.
4. It will crash.

## Log

https://gist.github.com/Mario3264/6ad1b9a63ecba0526fe8dc5b46799b7e

**Comment by Yamza** [comment]
not enough ram
`Memory: 2055109328 bytes (1959 MB) / 4984930304 bytes (4754 MB) up to 5726797824 bytes (5461 MB)`

https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/

**Comment by Mario3264** [comment]
I only have 8GB, and do you need to use the Java Launcher? I found that using the JVM argument ```-version:1.8+``` works fine in using the latest Java. The instructions were a bit unclear, is this where you set the "**5.5GB MINIMUM**"?: 
![image](https://user-images.githubusercontent.com/16366524/48962205-ac6c1300-ef31-11e8-8b9a-39a5e25ba105.png)

**Comment by Yamza** [comment]
5.5 is not enough. if you only have 8gb then close all other apps and set it to 6.5gb. Use all the settings as described in that guide, there is a video if it confuses you.

**Comment by Mario3264** [comment]
I have changed it to 6.5GB; I added the JVM arguments in the reddit post after the ```-version:1.8+``` argument, it will still probably work.

**Comment by Yoosk** [comment]
We are working on modpack to resolve issues with too big RAM allocation required.
